NexusMutual/smart-contracts

contracts/MemberRoles.sol, test/02_Membership.test.js, test/18_ClaimAssessment.test.js
See https://github.com/NexusMutual/nexus-mutual/issues/9
=> Switch membership

contracts/Governance.sol, contracts/ProposalCategory.sol, contracts/mocks/GovernanceMock.sol, contracts/mocks/ProposalCategoryMock.sol, migrations/3_deploy_nexusmutual.js, migrations/4_initialize_nexusmutual.js, test/01_NXMaster.test.js, test/12_Pool.test.js, test/14_ProposalCategory.test.js, test/15_BasicGovernance.test.js, test/17_GovernanceCases.test.js, test/21_ConfigureParams.test.js, test/22_UnlockFixes.test.js, test/utils/encoder.js, test/utils/ethTools.js, test/utils/gvProposal.js
Changes made:
1. Speed bump for proposals other than AB voted and AB swap
2. Ability of majority of BA to reject action execution within the speed bump period
3. Storage of function to be exucuted per category onchain
4. Minor other fixes
=> fixed governace action issues

test/06_Quotation.test.js
Fixed issue of test cases failing in travis
=> fixing travis issue

contracts/NXMDSValue.sol
Update according to:
https://docs.chain.link/docs/price-feeds-migration-august-2020
DAI/ETH | 0x773616E4d11A78F511299002da57A0a94577F1f4
=> update dai-eth aggregator address

contracts/Governance.sol, contracts/external/govblocks-protocol/interfaces/IGovernance.sol, test/15_BasicGovernance.test.js
- Remove dead code from Governance and IGovernance
- Remove corresponding "tests"
=> Remove dead Governance code

contracts/interfaces/IGovernance.sol, contracts/mocks/Disposables/DisposableGovernance.sol, contracts/modules/governance/Governance.sol, contracts/modules/governance/VotePower.sol, package-lock.json, package.json, test/fork/vote-power.js, test/unit/SwapOperator/transferToCommunityFund.js
Exposes an ERC20 interface and returns the amount of tokens held by the owner + balances of all members who delegated. Adds 1 NXM to everyone's balance as per spec. Can only be used against a snapshot as it doesn't check lock times hence doesn't prevent double voting if used on-chain.
=> Feature: vote power contract

package-lock.json, package.json
some issue with latest ethers breaking error parsing
https://ethereum.stackexchange.com/questions/125035/failed-require-causes-rangeerror-maximum-call-stack-size-exceeded
=> fix ethers to 5.6.0 and other test failures

.circleci/config.yml, contracts/modules/cover/Quotation.sol, hardhat.config.js, package-lock.json, package.json, test/fork/basic-functionality-tests.js, test/fork/cover-metadata-upgrade.js, test/fork/utils.js, test/integration/Quotation/buyCoverWithMetadata.js, test/integration/Quotation/index.js
- Add buy cover with metadata method
=> Release v1.6.0

contracts/modules/governance/Governance.sol, package.json
- Disable delegations in preparation for v2
=> Release 1.6.1

contracts/external/enzyme/IAddressRegistryList.sol, contracts/external/enzyme/IEnzymeFundValueCalculatorRouter.sol, contracts/external/enzyme/IEnzymePolicyManager.sol, contracts/external/enzyme/IEnzymeV4Comptroller.sol, contracts/external/enzyme/IEnzymeV4DepositWrapper.sol, contracts/external/enzyme/IEnzymeV4Vault.sol, contracts/external/enzyme/IWETH.sol, contracts/interfaces/IPriceFeedOracle.sol, contracts/mocks/Pool/P1MockEnzymeFundValueCalculatorRouter.sol, contracts/mocks/Pool/P1MockEnzymeV4Comptroller.sol, contracts/mocks/Pool/P1MockEnzymeV4DepositWrapper.sol, contracts/mocks/Pool/P1MockEnzymeV4Vault.sol, contracts/modules/capital/SwapOperator.sol, contracts/modules/claims/ClaimsReward.sol, contracts/modules/oracles/PriceFeedOracle.sol, package-lock.json, test/fork/enzyme-investment.js, test/fork/index.js, test/integration/Claims/index.js, test/integration/Claims/locktime.js, test/integration/Pool/token-price.js, test/integration/setup.js, test/unit/MCR/setup.js, test/unit/Pool/setup.js, test/unit/SwapOperator/index.js, test/unit/SwapOperator/recoverAsset.js, test/unit/SwapOperator/setup.js, test/unit/SwapOperator/swapETHForEnzymeVaultShare.js, test/unit/SwapOperator/swapEnzymeVaultShareForETH.js, test/utils/setupUniswap.js
- Implement enzyme vault integration
- Better claim assessment timelock checks
=> Release v1.7.0

docs/DISTRIBUTOR.md
=> Fix: typos

.github/pull_request_template.md
Redid https://github.com/NexusMutual/smart-contracts/pull/336 on top of `nexus-v2` branch.
Closes #285
=> Chore: Create PR template

contracts/modules/governance/MemberRoles.sol, contracts/modules/token/TokenController.sol, test/unit/TokenController/setup.js
Fixed audit issue: https://github.com/NexusMutual/smart-contracts/issues/323
Change modifiers for:
[MemberRoles::changeMaxABCount()](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/governance/MemberRoles.sol#L71)
[TokenController::changeOperator()](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/token/TokenController.sol#L54)
To be onlyGovernance as opposed to onlyInternal since that is the actual minimal permission necessary.
Run existing tests and make sure they don't fail.
The fix is quite minimal.
* …
=> Fix modifier for functions made for governance calls

test/integration/IndividualClaims/submitClaim.js, test/integration/MemberRoles/storageCleanup.js, test/integration/MemberRoles/switchMembership.js, test/integration/MemberRoles/switchMembershipAndAssets.js, test/integration/YieldTokenIncidents/submitClaim.js, test/integration/setup.js, test/integration/utils/enroll.js
Closes #291
Remove references to `withEthers`, `web3ToEthers`, `truffle`, `artifacts` and `web3` from integration test setup. 
No new tests added, all existing active integration tests passing, proving setup.js works as expected
=> Test: initialize with ethers remove truffle

test/unit/Assessment/helpers.js, test/unit/Assessment/setup.js, test/unit/Assessment/withdrawRewards.js, test/unit/Assessment/withdrawRewardsTo.js
Closes #429 
Adds new unit tests for `withdrawRewards` and `withdrawRewardsTo` implemented the list of test cases from the issue, with the following exceptions:
- `Should emit an event` was already implemented in another PR.
- `Should revert if the staker is not a member` in the case of `withdrawRewardsTo` there was already a test checking for the destination address.
- `Should correctly withdraw batched rewards` in the case of `withdrawRewardsTo` there was already a test checking that
New tests were added in `test/unit/Assessment/withdrawRewards.js` and `test/unit/Assessment/withdrawRewardsTo.js`
* …
=> Test/ Add Assessment withdrawRewards and withdrawRewardsTo unit tests

contracts/mocks/Assessment/ASMockTokenController.sol, contracts/modules/assessment/Assessment.sol, test/unit/Assessment/constructor.js, test/unit/Assessment/index.js, test/unit/Assessment/initialize.js, test/unit/Assessment/setup.js
Closes #432 
Adds new unit tests for the constructor and initialize. Implemented the list of test cases from the issue. `nxm` was changed to `public` to be able to fetch it for testing, and logic to test whitelisting was added to `ASMockTokenController`. 
New tests were added in `test/unit/Assessment/initialize.js` and `test/unit/Assessment/constructor.js`
=> Test/ Add constructor and initialize assessment tests

.solcover.js
Skipped view-only contracts from the test coverage tool and rearrange config files alphabetically. 
N/A
=> Chore: Update solcover config

contracts/mocks/TokenControllerMock.sol, test/unit/Cover/buyCover.js
Partial implementation of https://github.com/NexusMutual/smart-contracts/issues/268
Built on top of #449 
Implements the rest of the pending unit tests cases expect for the following ones that are going to be implemented as integration tests in a future PR:
- `Should correctly calculate premium`
- `Should correctly allocate capacity to pools`
New tests were added in `test/unit/Cover/buyCover.js`
=> Test: Add more buyCover unit tests

contracts/interfaces/IPool.sol, contracts/interfaces/ISwapOperator.sol, contracts/mocks/Pool/P1MockSwapOperator.sol, contracts/modules/capital/Pool.sol, contracts/modules/capital/SwapOperator.sol, contracts/modules/cover/Cover.sol, test/integration/setup.js, test/unit/Pool/getters.js, test/unit/Pool/sellNXMTokens.js, test/unit/Pool/setSwapDetailsLastSwapTime.js, test/unit/Pool/setup.js, test/unit/Pool/transferAssetToSwapOperator.js, test/unit/Pool/updateParameters.js, test/unit/SwapOperator/placeOrder.js, test/unit/SwapOperator/setup.js, test/unit/SwapOperator/swapETHForEnzymeVaultShare.js
Fixes https://github.com/NexusMutual/smart-contracts/issues/343
Add a check for orderInProgress() when upgrading SwapOperator when it's being replaced.
Remove getWei function.
Move `minPoolEth` to SwapOperator where it's the only place where it's used.
Pack   `uint96 public swapValue;` with `deprecatedCoverAssetsBitmap`.
Change failing tests so they pass given the new updates.
No new tests added.
=> Fix pool todos

test/integration/Cover/expireCover.js, test/integration/Cover/index.js, test/integration/index.js
Closes #278 
Relates to #468  
Adds the pending integration tests for the `expireCover` method.
New tests were added in `test/integration/Cover/expireCover.js`
=> Test: Add expireCover integration tests

contracts/modules/assessment/YieldTokenIncidents.sol, test/unit/YieldTokenIncidents/constructor.js, test/unit/YieldTokenIncidents/index.js, test/unit/YieldTokenIncidents/initialize.js, test/unit/YieldTokenIncidents/redeemPayout.js, test/unit/YieldTokenIncidents/submitIncident.js, test/unit/YieldTokenIncidents/withdrawAsset.js
Closes #434 
Adds new unit tests for `constructor`, `initialize`, `submitIncident`, `redeemPayout` and `withdrawAsset` of `YieldTokenIcidents`. Implemented the list of test cases from the issue with the exception of `Should emit IncidentPayoutRedeemed event` that was already implemented. I've change  visibility of `coverNFT` and `nxm` variables  to public in `YieldTokenIncidents.sol`.
Implemented test cases from the issue as described before.
=> Test/ YieldTokenIncidents tests

hardhat.config.js/networks.js, test/integration/YieldTokenIncidents/submitClaim.js, test/integration/setup.js, test/unit/Assessment/setup.js, test/unit/Assessment/withdrawRewards.js, test/unit/Assessment/withdrawRewardsTo.js, test/unit/Cover/setup.js, test/unit/CoverMigrator/setup.js, test/unit/IndividualClaims/redeemClaimPayout.js, test/unit/IndividualClaims/setup.js, test/unit/IndividualClaims/submitClaim.js, test/unit/MemberRoles/setup.js, test/unit/Pool/sellNXM.js, test/unit/Pool/sellNXMTokens.js, test/unit/StakingPool/setup.js, test/unit/SwapOperator/setup.js, test/unit/TokenController/setup.js, test/unit/YieldTokenIncidents/redeemPayout.js, test/unit/YieldTokenIncidents/setup.js, test/utils/accounts.js, test/utils/evm.js
Several test setup improvements to keep things clean.
- Removes hardcoded berlin hardfork and fixes the tests that failed due to zero gas fee txes
- Simplifies accounts and signers generation and usage
Only existing tests needed to pass.
=> Chore: tests housekeeping

.eslintrc, package-lock.json, package.json, test/fork/basic-functionality-tests.js, test/index.js, test/integration/Gateway/getters.js, test/unit/NXMaster/getters.js
Mocha was silently failing errors thrown inside describe statements and we only had a workaround, not a proper fix.
This PR adds a proper fix for mocha silently skipping errors in describes. The issue was async describes.
No added test. Tested locally to make sure async describe raises an eslint error.
=> Fix: no async describe

.eslintrc
Eslint improvement
Avoid commits of `.only`
N/A
=> Feature: Eslint avoid .only

contracts/interfaces/ICover.sol, contracts/interfaces/IStakingPool.sol, contracts/mocks/Cover/CoverMockStakingPool.sol, contracts/mocks/StakingPool/SPMockCover.sol, contracts/modules/cover/Cover.sol, contracts/modules/staking/StakingPool.sol, test/integration/setup.js, test/unit/Cover/buyCover.js, test/unit/Cover/setProducts.js, test/unit/Cover/setup.js, test/unit/StakingPool/setProducts.js
Issue:
https://github.com/NexusMutual/smart-contracts/issues/504
Add a flag for each product that specifies whether a product has fixed pricing, plus a list of whitelisted pool ids that the respective product capacity can be allocated to.
StakingPool.setProducts method now checks that the Pool's id is whitelisted if a product is a fixed price product.
Whenever capacity is allocated during a buyCover flow, a useFixedPricing flag is passed to the staking pool to apply the targetPrice to that cover for pricing and bypass the normal pricing formula.
A buyCover unit test is written for a fixed price product.
An integration test is necessary to test buyCover using a fixed price product. 
An integration test is necessary to test StakingPool.setProducts for a product that has fixedPricing = true …
=> Feature: support fixed price

contracts/interfaces/IPriceFeedOracle.sol, contracts/mocks/Disposables/DisposableNXMaster.sol, contracts/mocks/Testnet/TestnetNXMaster.sol, contracts/modules/capital/Pool.sol, contracts/modules/capital/PriceFeedOracle.sol, contracts/modules/governance/NXMaster.sol, contracts/modules/governance/external/OwnedUpgradeabilityProxy.sol, contracts/modules/governance/external/Proxy.sol, contracts/modules/governance/external/UpgradeabilityProxy.sol
PriceFeedOracle and Master contracts outdated
Closes #467 
Upgrading the PriceFeedOracle, Master and all relative contracts to 0.8.16.
N/A
=> Chore: Upgrade PriceFeedOracle and Master contract

test/integration/IndividualClaims/submitClaim.js, test/integration/Master/emergency-pause.js, test/integration/YieldTokenIncidents/submitClaim.js, test/integration/setup.js, test/integration/utils/cover.js, test/integration/utils/voteClaim.js
Closes #294 
Adds new integration tests for the process of submitting a claim and redeeming the payout.
New tests were added in `test/integration/IndividualClaims/submitClaim.js`
=> Test: Integration tests for submitClaim (IndividualClaims)

contracts/mocks/Assessment/ASMockYieldTokenIncidents.sol, contracts/modules/assessment/YieldTokenIncidents.sol, test/unit/Assessment/helpers.js, test/unit/Assessment/startAssessment.js, test/unit/IndividualClaims/helpers.js, test/unit/YieldTokenIncidents/helpers.js, test/unit/YieldTokenIncidents/initialize.js, test/unit/YieldTokenIncidents/updateUintParameters.js
Discovered while extracting the config params so we can tune their values.
- Remove `expectedPayoutRatio` param 
- Update the signature of `submitIncident()` function in `mocks/Assessment/ASMockYieldTokenIncidents.sol`
- Update existing unit tests accordingly
All existing tests pass.
=> Chore: Remove unused param in incidents config and update tests accordingly

test/unit/StakingPool/extendDeposit.js
I've noticed some staking related tests started failing on a clean branch I just created. 
Move to the beginning of the next tranche in `beforeEach`
All tests pass
=> Test: Fix tranches setup in unit tests

contracts/interfaces/IPool.sol, contracts/modules/capital/Pool.sol
A bit of cleanup, as highlighted in the audit report.
- remove duplicate code
- remove unused function `transferAssetFrom` - previously used only in Quotation.sol
- grouped functions in the following categories, for easier navigation through the contract:
- Asset related functions
- Swap Operator related functions
- Claims related function	
- Token related functions
- Upgrade related functions
**NOTE**: Best way to review this diff is commit by commit.
All existing tests pass.
* :thinking: = I don’t understand something, do you mind giving me more …
=> Chore: Pool.sol cleanup

contracts/modules/assessment/IndividualClaims.sol, contracts/modules/assessment/YieldTokenIncidents.sol, contracts/modules/cover/Cover.sol, test/unit/Cover/buyCover.js, test/unit/IndividualClaims/initialize.js, test/unit/YieldTokenIncidents/initialize.js
Did a final review with Hugh. Full values can be found here: https://docs.google.com/document/d/1zds4YLHql1TG3riZtGGwQfCR4MMlZqX6qoLhfpFq1j4/edit#
- `Cover.sol`: `MAX_COMMISSION_RATIO` changes from `25%` to `30%`
- `IndividualClaims.sol`: `payoutRedemptionPeriod` changes from `14 days` to `30 days`
- `YieldTokenIncidents.sol`: `payoutRedemptionPeriod` changes from `14 days` to `30 days`
-
=> Chore: Update param values

contracts/modules/assessment/IndividualClaims.sol, contracts/modules/cover/Cover.sol, contracts/modules/cover/CoverMigrator.sol, contracts/modules/staking/StakingPool.sol, contracts/modules/token/TokenController.sol, test/integration/setup.js, test/unit/Cover/createStakingPool.js, test/unit/CoverMigrator/index.js, test/unit/CoverMigrator/migrateCoverFrom.js, test/unit/CoverMigrator/migrateCovers.js, test/unit/StakingPool/constructor.js, test/unit/StakingPool/depositTo.js, test/unit/StakingPool/extendDeposit.js, test/unit/StakingPool/setup.js, test/unit/StakingPool/withdraw.js, test/unit/TokenController/withdrawGovernanceRewards.js, test/unit/TokenController/withdrawGovernanceRewardsTo.js, test/unit/TokenController/withdrawPendingRewards.js
Closes https://github.com/NexusMutual/smart-contracts/issues/330
Final list of emergency pause check enforcements: https://docs.google.com/document/d/1eOXf1FSWlSVKW1ZhvSANpQeYQ5mk4HP3SMtriN4zxyE/edit#. 
Please take a moment to review and let me know if you think I missed something.
Added test cases for all added modifiers, expect for the ones in TokenController.sol. Those will be addressed as part of https://github.com/NexusMutual/smart-contracts/issues/346https://github.com/NexusMutual/smart-contracts/issues/346
* :thinking: = I don’t understand …
=> Feat: Add emergency pause checks & tests

test/fork/evm.js, test/fork/migration-v2.js, test/fork/utils.js, test/utils/evm.js
Ability to run fork tests on either tenderly and hardhat.
Ran locally.
=> Feature: evm helper for fork tests

scripts/deploy/deploy.js
Oops, i accidentally everything...
=> Prevent config file overwrite

test/unit/Cover/editCover.js
Closes #442 
Built on top of #618 
Adds new unit tests for `buyCover` for editing covers scenarios
New tests were added in `test/unit/Cover/editCover.js`
=> Test: Add edit cover unit tests

test/unit/StakingPool/requestAllocation.js
2 `requestAllocation` unit tests fails with `InsufficientCapacity()`. 
Increase the target tranche for the initial deposit in the setup of the tests. Some unit tests use long periods of time for allocation, based on the current time the allocation could use a tranche that does have no deposits. The new value should be enough for all the existing tests.
* :thinking: = I don’t …
=> Fix: update setup for request allocation broken unit test

test/unit/StakingPool/withdraw.js
The test includes a check that considers a 10 wei rounding error, and the error is 11 wei.
Temporarily skipped the test to be able to merge other PRs.
=> Temporarily skip failing staking withdraw test

test/unit/StakingPool/requestAllocation.js
Failure reason not obvious but might be related to the recent `const trancheOffset = 4` -> `const trancheOffset = 5` change
Temporarily skipped.
=> Temporarily skipping last bucket id test

contracts/modules/governance/MemberRoles.sol, test/fork/migration-v2.js, test/unit/MemberRoles/stateManagement.js
…Address`
Issue: #438 
Expanding `storageCleanup` function with array of addresses that will be used to clear the `claimPayoutAddress` mapping for those addresses
Expanded fork test for the change, also fixed failing unit test for `storageCleanup`
=> Feature: Expanding `storageCleanup` with addresses to be Zeroed

contracts/interfaces/ICover.sol, contracts/interfaces/IStakingPool.sol, contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/helpers.js, test/unit/StakingPool/processExpirations.js, test/unit/StakingPool/requestAllocation.js
=> Feature: Pack StakingPool structs and change RewardBuckets to regular uint

contracts/interfaces/IStakingPool.sol, contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/initialize.js, test/unit/StakingPool/setProducts.js
Closes #653 
- added 2 new events: `ProductUpdated` and `StakeBurned`
- updated the args of `PoolDescriptionSet` event to remove `poolId`, is it seems redundant
- added a test for `ProductUpdated` and left `StakeBurned` for #564 
All tests pass, added new unit test
=> Feat: Added events on StakingPool.sol

contracts/interfaces/IStakingPool.sol, contracts/modules/staking/StakingViewer.sol
=> Implement StakingViewer based on discussions and needs

contracts/interfaces/ITokenController.sol, contracts/mocks/Disposables/DisposableGovernance.sol, contracts/mocks/Master/MMockNewContract.sol, contracts/mocks/Master/MSMockGovernance.sol, contracts/mocks/NXMTokenMock.sol, contracts/mocks/Pool/P1MockEnzymeFundValueCalculatorRouter.sol, contracts/mocks/Pool/P1MockEnzymeV4Comptroller.sol, contracts/mocks/Pool/P1MockEnzymeV4DepositWrapper.sol, contracts/modules/claims/Claims.sol, contracts/modules/claims/ClaimsReward.sol, contracts/modules/claims/Incidents.sol, contracts/modules/cover/Quotation.sol, contracts/modules/token/TokenController.sol, test/fork/one-time-partial-claims.js, test/fork/utils.js, test/integration/Claims/dai-payouts.js, test/integration/Claims/eth-payouts.js, test/integration/Gateway/getters.js, test/unit/TokenController/index.js, test/unit/TokenController/markCoverClaim.js
[#654](https://github.com/NexusMutual/smart-contracts/issues/654)
- Implements partial claims on top of V1. Once the claim is accepted - the cover is no longer usable.
- Removes the status 12 (payout pending) by reverting when the payout fails in order to remove the retrying logic
Added new tests. Fixed the failing status 12/13/14 tests.
=> Feature: v1 partial claims

contracts/mocks/TokenController/TCMockAssessment.sol, contracts/mocks/TokenController/TCMockStakingPool.sol, test/unit/TokenController/setup.js, test/unit/TokenController/withdrawPendingRewards.js
Partial implementation of #346 
Adds new unit tests for `TokenController.withdrawPendingRewards()`
New tests were added in `test/unit/TokenController/withdrawPendingRewards.js`
=> Test: Add token controller withdrawPendingRewards unit tests

test/unit/TokenController/burnStakedNXM.js, test/unit/TokenController/burnStakingPoolNXMRewards.js, test/unit/TokenController/depositStakedNXM.js, test/unit/TokenController/index.js, test/unit/TokenController/mintStakingPoolNXMRewards.js, test/unit/TokenController/setup.js, test/unit/TokenController/withdrawNXMStakeAndRewards.js
Partial implementation of https://github.com/NexusMutual/smart-contracts/issues/346
Adds new unit tests for:
- burnStakedNXM()
- burnStakingPoolNXMRewards()
- depositStakedNXM()
- mintStakingPoolNXMRewards()
- withdrawNXMStakeAndRewards()
New tests were added in:
- `test/unit/TokenController/burnStakedNXM.js`
- `test/unit/TokenController/burnStakingPoolNXMRewards.js`
- `test/unit/TokenController/depositStakedNXM.js`
- `test/unit/TokenController/mintStakingPoolNXMRewards.js`
- `test/unit/TokenController/withdrawNXMStakeAndRewards.js`
* :thinking: = I don’t …
=> Test: Add token controller stake and rewards unit tests

contracts/interfaces/IStakingPool.sol, contracts/mocks/Cover/CoverMockStakingPool.sol, contracts/modules/legacy/LegacyPooledStaking.sol, contracts/modules/staking/StakingPool.sol, contracts/modules/staking/StakingViewer.sol, scripts/deploy/deploy.js, test/unit/StakingPool/burnStake.js, test/unit/StakingPool/depositTo.js, test/unit/StakingPool/extendDeposit.js, test/unit/StakingPool/helpers.js, test/unit/StakingPool/initialize.js, test/unit/StakingPool/processExpirations.js, test/unit/StakingPool/requestAllocation.js, test/unit/StakingPool/setPoolFee.js, test/unit/StakingPool/setProducts.js, test/unit/StakingPool/withdraw.js
Implements https://github.com/NexusMutual/smart-contracts/issues/333
Serves current UI data fetching needs.
For now Andreea and Gideon test it on the UI side. I will add tests as well at a later point, after more urgent issues are completed.
=> Feat: Staking viewer contract

contracts/mocks/StakingNFT/SNFTMockCover.sol, test/unit/StakingNFT/setup.js, test/unit/StakingNFT/stakingNFT.js, test/unit/StakingPoolFactory/index.js, test/unit/StakingPoolFactory/setup.js, test/unit/StakingPoolFactory/stakingPoolFactory.js, test/unit/index.js
Closes #552 
Added unit tests for `StakingNFT` and `StakingPoolFactory` contracts
Added tests to:
`test/unit/StakingPoolFactory/stakingPoolFactory.js`
`test/unit/StakingNFT/stakingNFT.js`
=> Test: Add unit tests for StakingNFT and StakingPoolFactory

contracts/mocks/Disposables/DisposableMemberRoles.sol, contracts/mocks/Disposables/DisposableTokenController.sol, contracts/modules/capital/Pool.sol, contracts/modules/governance/MemberRoles.sol, contracts/modules/token/TokenController.sol, test/fork/migration-v2.js, test/integration/Master/emergency-pause.js, test/integration/Master/master.js, test/integration/setup.js, test/unit/MemberRoles/changeDependentContractAddress.js, test/unit/MemberRoles/setup.js, test/unit/Pool/setup.js, test/unit/Pool/upgradeCapitalPool.js, test/unit/SwapOperator/setup.js, test/unit/TokenController/setup.js
This was causing issues with the upgrade of TC and CR and required us to be extra careful at launch.
Make the token address immutable in TokenController.sol
All existing tests oass
=> Chore: Make token immutable in TokenController.sol, MemberRoles.sol, Pool.sol

contracts/modules/governance/Governance.sol, test/fork/index.js, test/fork/reject-actions.js
=> RejectAction improvement

contracts/modules/staking/StakingViewer.sol, scripts/deploy/deploy.js, scripts/mocks/createStakingPools.js
Closes #697
Make the function accept a list of `poolId`s and return `Token[]` instead.
n/a
=> Feat: Update StakingViewer.getManagerRewards() implementation

contracts/interfaces/IProductsV1.sol, contracts/modules/legacy/LegacyPooledStaking.sol, test/fork/migration-v2.js
Cleanup PS migration code
- renames for clarity
- remove unused struct
- move struct and constants at the beginning of the file
- indentation fixes
- bug fix where we were creating the staking pools by setting the manager address to be the staker address (they are different for Armor)
- added logic to prevent dust due to division errors
Ran fork test
=> Chore: Cleanup PS migration code and fix bugs

contracts/modules/legacy/LegacyPooledStaking.sol, test/fork/migration-v2.js
=> Some more cleanup in PS & PS migration code

contracts/modules/governance/Governance.sol, test/fork/reject-actions.js
Partial implementation of [#708](https://github.com/NexusMutual/smart-contracts/issues/708)
Cherrypicked Governance changes for ActionFailed improvement
Ran existing tests
=> Chore: Cherrypick ActionFailed mainnet releaase

contracts/interfaces/ITokenController.sol, contracts/mocks/CoverMigrator/CMMockTokenController.sol, contracts/modules/cover/CoverMigrator.sol
Closes https://github.com/NexusMutual/smart-contracts/issues/708
Cherrypick TC-related changes from release 1.7.1
Ran existing tests
=> Cheerypick TC changes from release 1.7.1

contracts/interfaces/ICoverNFT.sol, contracts/interfaces/IStakingNFT.sol, contracts/modules/cover/CoverNFT.sol, contracts/modules/staking/StakingNFT.sol, test/unit/CoverNFT/coverNFT.js, test/unit/StakingNFT/stakingNFT.js
Closes #677 
- Changed require statements to custom errors
- Moved solmate erc721 into `CoverNFT` contract and removed unused functions
=> Feature: Custom error nfts

contracts/modules/capital/Pool.sol, contracts/modules/token/TokenController.sol
Extracted the smart contract changes from #640 separately.
- Fixes TokenController storage layout
- Fixes the DAI params in Pool
Fork tests stay in #640. No unit/integration test changes required.
=> TC storage fix and pool dai params

contracts/modules/cover/Cover.sol, contracts/modules/cover/CoverNFT.sol, contracts/modules/staking/StakingNFT.sol, contracts/modules/staking/StakingViewer.sol, scripts/mocks/buyV2Covers.js, scripts/mocks/depositToStakingPools.js
- Fixed deploy script and UI mocks related scripts
- Fixed warnings recently introduced
=> Chore: Fix warnings and UI-mocks related scripts

contracts/modules/claims/ClaimsReward.sol, contracts/modules/cover/Quotation.sol, test/fork/disable-active-cover-amount-tracking.js, test/integration/MCR/getMCR.js, test/integration/MCR/updateMCR.js, test/integration/Quotation/expireCover.js
Disable total active cover amount tracking ahead of v2 launch.
Comment out active cover amount subtraction on claim expiration and payout.
Skipped relevant MCR tests (we're not going to hit gear soon so it doesn't impact us). Added fork test.
=> Fix: v1 active amount tracking

contracts/modules/claims/ClaimsReward.sol, contracts/modules/cover/Quotation.sol, package-lock.json, package.json, test/fork/disable-active-cover-amount-tracking.js, test/integration/MCR/getMCR.js, test/integration/MCR/updateMCR.js, test/integration/Quotation/expireCover.js
=> Release v1.7.3

contracts/modules/capital/MCR.sol
Closes issue https://github.com/NexusMutual/smart-contracts/issues/738
Replace duplicate implementations of min/max functions with the ones from Math.sol
n/a
=> Replace min/max with the functions from the Math library

scripts/deploy/deploy.js
See https://github.com/NexusMutual/frontend-react/issues/880
Called `changeDependentContractAddress` for Assessment contract deployment.
Run deploy script => call `castVotes` method
=> Fix assessment contract deploy issue

contracts/interfaces/ICover.sol, contracts/mocks/Claims/CLMockCover.sol, contracts/mocks/CoverViewer/CVMockCover.sol, contracts/mocks/Incidents/ICMockCover.sol, contracts/modules/assessment/IndividualClaims.sol, contracts/modules/assessment/YieldTokenIncidents.sol, contracts/modules/cover/Cover.sol, contracts/modules/cover/CoverViewer.sol, test/integration/Cover/totalActiveCover.js, test/integration/IndividualClaims/submitClaim.js, test/unit/Cover/burnStake.js, test/unit/Cover/buyCover.js, test/unit/Cover/editCover.js, test/unit/Cover/helpers.js, test/unit/CoverViewer/setup.js, test/unit/CoverViewer/views.js
Closes https://github.com/NexusMutual/smart-contracts/issues/418
Clean up the implementation of getCovers used in the UI:
- restructured the data
- removed product / product type related info that already exists in state
- removed commented code
- removed unused functions
None yet
=> Reimplement getCovers in CoverViewer

contracts/interfaces/ITokenController.sol, contracts/mocks/Disposables/DisposableTokenController.sol, contracts/modules/token/TokenController.sol, test/unit/TokenController/withdrawPendingRewards.js
Needed for the UI, so users can see how many tokens they have in V1 claim assessment.
Made the existing function public
N/A
=> Chore: Make TC.tokensLocked function public

contracts/interfaces/ICover.sol, contracts/modules/cover/Cover.sol, test/integration/setup.js, test/unit/Cover/setup.js
Latest PRs increased Cover size past limit again.
- make more constants private
- remove IC unused dependency
- made max cover period 365 days instead of 364 (with @shark0der 's blessing)
Ran existing tests
=> Reduce cover size & update max cover period to 365 days

contracts/modules/cover/CoverViewer.sol
Return a tiny bit of extra data for convenience purposes in the frontend
=> Add coverId to covers in CoverViewer#getCovers

contracts/mocks/Cover/CoverMockStakingPool.sol, contracts/mocks/Cover/CoverMockStakingProducts.sol, test/unit/Cover/createStakingPool.js, test/unit/Cover/setup.js
Closes #701 
Added some assertions to check that the parameters are initialized during `cover.createStakingPool()` call
=> Test: create staking pool unit tests

contracts/modules/cover/Cover.sol, test/integration/IndividualClaims/submitClaim.js, test/unit/Cover/editCover.js, test/unit/Cover/index.js, test/unit/Cover/totalActiveCoverInAsset.js
This codepath still has high risk issues reported in the audit and requires more attention before it can be production ready.
Disable the functionality and skip corresponding tests.
N/A
=> Chore: disable edit cover for launch

contracts/modules/governance/NXMaster.sol, test/fork/migration-v2.js
Remove the need to have a separate proposal to upgrade GV - there is no point.
- upgrade GV in batch with the other contracts
- move token assertions after the upgrade
- add back dappLocker so e can actually run the upgrade like this
Fork test
=> Fix: Make the GV upgrade together with the other contracts 

contracts/modules/cover/Cover.sol, test/integration/MCR/getAllSumAssurance.js, test/integration/MCR/getMCR.js, test/integration/MCR/updateMCR.js, test/integration/Pool/token-price.js, test/integration/setup.js, test/integration/utils/assetPricing.js, test/integration/utils/cover.js, test/integration/utils/staking.js, test/integration/utils/voteClaim.js
=> Test: mcr integration skipped tests - totalActiveCover

lib/constants.js, lib/proposal-categories.js, test/fork/basic-functionality-tests.js, test/fork/migration-v2.js, test/fork/utils.js
=> Migration: Basic Functionality Tests for V2 upgrade

contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/helpers.js, test/unit/StakingPool/withdraw.js
=> Test: fix accumulator tests

contracts/modules/cover/Cover.sol, contracts/modules/staking/StakingPool.sol
Started as a re-review of the burn functionality. Scope is to make sure it works well when covers have a single segment.
- Cover contract changes are only renames and comments
- Staking contract changes, besides renames and comments, include a small optimization where if at least one tranche has expired since the cover was bought - do not modify the amounts on it.
I believe the existing coverage should suffice. No tests have failed.
=> Chore: burn review

contracts/modules/cover/ProductsV1.sol, scripts/v2-migration/generate-v2-products-txs.js, scripts/v2-migration/get-v2-products.js, scripts/v2-migration/input/product-data.csv, scripts/v2-migration/output/v2-products-map.json, scripts/v2-migration/upload-to-ipfs.js, test/fork/migration-v2.js
Issue: https://github.com/NexusMutual/smart-contracts/issues/699
https://github.com/NexusMutual/smart-contracts/issues/767
**Changes proposed in this pull request**
Generate the txs for setProducts/setProductTypes and use them in the fork
Migrate FTX covers that are still usable - not expired.
**Test plan**
Run the fork + a few extra assertions for products.
=> Migration: Add file for tx generation + updated product data

scripts/mocks/createStakingPools.js, test/fork/migration-v2.js
Added demo hashes to `createStakingPools.js` to prevent `undefined` pool names and descriptions in the frontend when developing locally.
=> Add ipfs hashes to createStakingPools.js script

contracts/modules/staking/StakingViewer.sol
Rewards fetching is lagging because there's no way for the UI to trigger `processExpirations(true)`.
This PR adds that function so it can be used in a `multicall()`
=> Add processExpirations function on StakingViewer contract

contracts/modules/staking/StakingViewer.sol
In title.
Multiplied by 1e18 to return a number with higher precision.
=> Fix StakingViewer APY always returning sub-unit values

hardhat.config.js/index.js
Compiling without optimizer enabled always fail because of the contract size
Adding check if the optimizer is enabled, if it is convert `code-size` to error instead or warning
N/A
=> Chore: Adding optimizer check for code-size error

contracts/mocks/StakingProducts/StakingProductsMockCover.sol, test/unit/StakingProducts/getEffectiveWeight.js, test/unit/StakingProducts/helpers.js, test/unit/StakingProducts/index.js, test/unit/StakingProducts/initializeProducts.js, test/unit/StakingProducts/recalculateEffectiveWeight.js, test/unit/StakingProducts/setProducts.js, test/unit/StakingProducts/setup.js
Closes [#791](https://github.com/NexusMutual/smart-contracts/issues/791)
- Added more testing around staked product weights
=> Test: add more testing around effective weight calculations

contracts/interfaces/IMasterAwareV2.sol, test/fork/basic-functionality-tests.js, test/fork/index.js, test/fork/run-basic-functionality-tests.js, test/fork/utils.js
Expand the basic functionality tests to verify production happy paths to include things that are not covered yet, like assessment, buying protocol and yield cover, emergency pause etc.
Issue: https://github.com/NexusMutual/smart-contracts/issues/614
Add fork tests covering:
* asessment and paying out of protocol, custodian and yield token cover
* emergency pause 
Verify all contract deps in internalContracts for implementors of MasterAwareV2 are updated correctly post-upgrade.
Expand the fork test set is the purpose of this PR.
* :thinking: = I don’t …
=> Test: add basic functionality test case updates

contracts/external/enzyme/IEnzymeV4Vault.sol, contracts/interfaces/ICowSettlement.sol, contracts/mocks/SwapOperator/SOMockEnzymeV4Vault.sol, contracts/modules/capital/SwapOperator.sol, hardhat.config.js/networks.js, test/fork/cowswap-swaps.js, test/fork/index.js
Issues:
https://github.com/NexusMutual/smart-contracts/issues/837
https://github.com/NexusMutual/smart-contracts/issues/450
Evaluating on a fork test that cowswap swaps work.
No smart contract code changes required except some interface enhancements. (no bugs found)
Write a fork test that tests a swap from ETH to DAI and a swap from DAI to ETH.
=> Test: cowswap prod swaps

test/integration/Governance/categorizeProposal.js, test/integration/Governance/closeProposal.js, test/integration/Governance/createProposal.js, test/integration/Governance/createProposalwithSolution.js, test/integration/Governance/index.js, test/integration/Governance/proposalFixture.js, test/integration/Governance/state.js, test/integration/Governance/submitProposalWithSolution.js, test/integration/Governance/submitVote.js, test/integration/Governance/submitVoteWithoutDelegations.js, test/integration/Governance/updateProposal.js, test/integration/Governance/updateUintParametars.js, test/integration/Master/emergency-pause.js, test/integration/Master/master.js, test/integration/index.js, test/integration/setup.js, test/integration/utils/enroll.js
#852 
Add tests for the Governance test
N/A
=> Add tests for Governance

scripts/products/generate-product-types-tx.js
Create a standalone-script to add new product types that also handles IPFS downloads.
Modify the migration script to handle this functionality.
Manual testing.
=> Script: generate tx for product types

contracts/modules/staking/StakingProducts.sol, deployments/.gitignore, deployments/build.js, deployments/package.json, deployments/src/index.ts, deployments/tsconfig.json, package-lock.json, package.json
Release 2.3.0
Release adds support for typescript to the deployment package and fixes a minor argument order isssue in the smart contracts.
=> Release v2.3.0

contracts/interfaces/IRamm.sol, contracts/modules/capital/Ramm.sol, test/unit/Ramm/setup.js
A few fixes added to the leftover branch. Best to review commit by commit.
=> Fixes: leftover adjustments

contracts/modules/capital/Ramm.sol
=> Fix time elapsed calculation for twap

test/unit/Ramm/getReserves.js, test/unit/Ramm/storeState.js
Add missing budget == 0 unit tests for getReserves and storeState
* getReserve inject ETH branch budget == 0
* storeState should update ratchetSpeed to NORMAL_RATCHET_SPEED if budget == 0
=> Add zero budget unit test - getReserves / storeState

contracts/interfaces/IMCR.sol, contracts/mocks/Cover/CoverMockMCR.sol, contracts/mocks/Disposables/DisposableMCR.sol, contracts/mocks/Pool/P1MockMCR.sol, contracts/mocks/Ramm/RammMockMCR.sol, contracts/modules/capital/MCR.sol, contracts/modules/capital/Pool.sol, lib/constants.js, package.json, test/integration/MCR/getMCR.js, test/integration/MCR/getTotalActiveCoverAmount.js, test/integration/MCR/updateMCR.js, test/integration/setup.js, test/unit/MCR/common.js, test/unit/MCR/updateMCR.js, test/unit/MCR/updateParameters.js
#903 
Remove MCR floor from the MCR contract
=> Feature: Remove MCR floor

contracts/interfaces/IRamm.sol, contracts/modules/capital/Ramm.sol, test/unit/Ramm/getInternalPrice.js, test/unit/Ramm/helpers.js
Adding external getInternalPrice method as a view so other contracts can use it in the view function
=> Add getInternalPrice method without update

contracts/modules/capital/Ramm.sol
Refactor - remove var mutation on swapEthForNxm and swapNxmForEth functions for better readability
* remove var mutation on swapEthForNxm
* remove var mutation on swapNxmForEth
* This MR is behind https://github.com/NexusMutual/smart-contracts/pull/965
* This should be pointed to `feature/tokenomics` once https://github.com/NexusMutual/smart-contracts/pull/965 is merged
* …
=> Feature/tokenomics Refactor remove var mutation on swap functions

contracts/modules/capital/Ramm.sol
Thought it might be a good idea to add ABI functions annotations for better documentation
* This MR is behind https://github.com/NexusMutual/smart-contracts/pull/968
* This should be pointed to `feature/tokenomics` once https://github.com/NexusMutual/smart-contracts/pull/968 is merged
Add NatSpec function annotation for ABI external functions:
**VIEW:**
* getReserves
* getSpotPrices
* getBookValue
**MUTATION:**
* updateTwap
* getInternalPriceAndUpdateTwap
* swap
* removeBudget
* setEmergencySwapPause
* :cake: = Nice to have but …
=> Add Ramm.sol ABI functions annotations

contracts/modules/capital/Pool.sol, test/integration/Master/master.js, test/integration/setup.js, test/unit/Pool/setup.js, test/unit/Pool/upgradeCapitalPool.js, test/unit/SwapOperator/setup.js
=> Remove swapValue from pool constructor and remove unused variables

contracts/modules/capital/Ramm.sol
Issue: #989 
Add ACCUMULATOR_PRECISION to the Ramm contract for readability
=> Feature: Tokenomics accumulator precision

contracts/interfaces/IPool.sol, contracts/mocks/common/EtherRejecterMock.sol, contracts/mocks/common/PoolEtherRejecterMock.sol, contracts/mocks/common/PoolMock.sol, contracts/mocks/common/RammMock.sol, contracts/modules/assessment/IndividualClaims.sol, contracts/modules/assessment/YieldTokenIncidents.sol, contracts/modules/capital/Pool.sol, contracts/modules/capital/Ramm.sol, contracts/modules/cover/Cover.sol, test/unit/IndividualClaims/redeemClaimPayout.js, test/unit/IndividualClaims/setup.js, test/unit/YieldTokenIncidents/redeemPayout.js, test/unit/YieldTokenIncidents/setup.js
Add update twap in Cover, IndividualClaims and YieldTokenIncidents
=> Feature: Tokenomics update twap

contracts/modules/capital/Ramm.sol
Code refactor audit [proposal]((https://iosiro.notion.site/Code-Quality-b2bce719d53545ed8dac7cc21f3fbe79)).
Break down the larger functions to smaller functions to aid readability and avoid code duplication.
This is behind PR #1002. Should be rebased and pointed to `feature/tokenomics` once #1002 is merged
* getObservation
* add new internal pure **calculatePriceCumulative** function
* _getReserves
* add new internal pure **calculateInjected** function
* add new internal pure **adjustEth** function
* add new internal pure **calculateNxm** function
Since all the new functions are internal functions and only used on **getObservation** and **_getReserves** functions we are relying on the current unit tests that was written both functions.
The current unit tests passing means that we have …
=> refactor: Audit Ramm code refactor

contracts/mocks/common/PoolMock.sol, contracts/modules/capital/Ramm.sol, test/integration/Cover/buyCover.js, test/integration/setup.js, test/integration/utils/enroll.js, test/unit/Ramm/getInternalPrice.js, test/unit/Ramm/getInternalPriceAndUpdateTwap.js, test/unit/Ramm/getObservation.js, test/unit/Ramm/getReserves.js, test/unit/Ramm/helpers.js, test/unit/Ramm/setup.js, test/unit/Ramm/swap.js, test/unit/Ramm/updateTwap.js
Missing min and max internal price
Add min and max for the internal price
=> Feature: Tokenomics min max internal price and update initial twap values

contracts/interfaces/IRamm.sol, contracts/modules/capital/Ramm.sol, test/integration/Ramm/swap.js, test/unit/Ramm/getInternalPrice.js, test/unit/Ramm/getInternalPriceAndUpdateTwap.js, test/unit/Ramm/getObservation.js, test/unit/Ramm/getReserves.js, test/unit/Ramm/getSpotPrices.js, test/unit/Ramm/helpers.js, test/unit/Ramm/storeState.js, test/unit/Ramm/swap.js, test/utils/internalPrice.js
information.
Pass params from swap to ther rest of the methods in a struct
=> Feature: ramm context struct (reuse-results)

contracts/modules/capital/Ramm.sol, test/unit/Ramm/setup.js
=> Feature: Tokenomics - internal constants

contracts/interfaces/IRamm.sol, contracts/modules/capital/Ramm.sol, test/unit/Ramm/getInternalPrice.js, test/unit/Ramm/getReserves.js, test/unit/Ramm/helpers.js, test/unit/Ramm/loadState.js, test/unit/Ramm/setup.js, test/unit/Ramm/storeState.js, test/unit/Ramm/swap.js
=> Fix: use correct ratchet speed

test/layout/selectors.js, test/layout/slots.js, test/layout/storage/previousLayout.json
Layout tests still compare V1 with V2 layout
Add new contracts to checklist and generate new layout out of the release candidate
=> Test: Update layout tests with new versions

contracts/interfaces/IRamm.sol, contracts/modules/capital/Ramm.sol, test/unit/Ramm/getInternalPrice.js, test/unit/Ramm/getObservation.js, test/unit/Ramm/helpers.js, test/utils/rammCalculations.js
=> Feature: Tokenomics observation packing

contracts/modules/capital/Ramm.sol, test/unit/Ramm/helpers.js, test/utils/rammCalculations.js
=> Feature: Tokenomics injection extraction fix

contracts/interfaces/IRamm.sol, contracts/libraries/SafeUintCast.sol, contracts/mocks/Disposables/DisposableRamm.sol, contracts/modules/capital/Ramm.sol, test/unit/Ramm/helpers.js, test/unit/Ramm/storeState.js
=> Repack Ramm storage

contracts/mocks/Disposables/DisposableTokenController.sol, contracts/modules/token/TokenController.sol
=> Fix: Prevent disposable tc from enrolling itself and improve mint checks

contracts/modules/capital/Pool.sol, contracts/modules/token/TokenController.sol
=> Chore: cleanup

contracts/modules/capital/Ramm.sol, test/fork/tokenomics.js, test/integration/Cover/buyCover.js, test/integration/MCR/updateMCR.js, test/unit/Cover/burnStake.js
=> Feature: Tokenomics skipped tests

contracts/modules/assessment/Assessment.sol, test/integration/Assessment/processFraud.js
=> Skip redundant iterations

contracts/modules/cover/Cover.sol, test/integration/Cover/expireCover.js
information.
Remove update of `activeCoverExpirationBuckets` from expire cover, so `buyCover` would catch it and update the total cover amount
=> Fix: Total Cover Amount

contracts/mocks/Testnet/TestnetMemberRoles.sol, scripts/deploy/whitelist.js
Created this draft for visibility. I'm not sure if we want this code in the repo, could merge just so we can use for future UI testing needs.
Run with `HARDHAT_NETWORK=tenderly node scripts/deploy/whitelist.js`
=> Add testnet MR patching code

contracts/interfaces/IMemberRoles.sol, contracts/modules/assessment/Assessment.sol, contracts/modules/cover/Cover.sol, contracts/modules/governance/MemberRoles.sol, contracts/modules/staking/StakingPool.sol, package-lock.json, test/integration/Assessment/processFraud.js, test/integration/Cover/expireCover.js, test/integration/MemberRoles/withdrawMembership.js, test/unit/Cover/processExpiredCover.js, test/unit/Cover/updateTotalActiveCoverAmount.js, test/unit/MemberRoles/withdrawMembership.js, test/unit/StakingPool/extendDeposit.js
=> Fixes: Release 2.5.0 (merge to rc)

contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/withdraw.js
=> Process expirations up to current time

contracts/mocks/modules/StakingPool/SKMockCover.sol, contracts/mocks/modules/StakingPool/SKMockCoverProducts.sol, contracts/mocks/modules/StakingPool/SKMockStakingNFT.sol, contracts/mocks/modules/StakingPool/SKMockStakingProducts.sol, test/unit/StakingPool/setup.js, test/unit/StakingProducts/setup.js
Issue: #1103 
Rename the StakingPool Mock contracts
=> chore: Rename StakingPool Mocks

scripts/products/get-setProductTypes-txdata.js, scripts/products/get-setProducts-txdata.js, scripts/products/helpers.js
Missing simluation tx and data verification of the transaction
Add simulation tx for tenderly and verify the data
=> chore: Add tenderly simulation and data verification for `setProductTypes`

contracts/modules/staking/StakingPool.sol
Issue: #1153 
- Remove hot fix for pool 8
N/A
=> Chore: Remove pool 8 bug fix

scripts/products/get-setProductTypes-txdata.js, scripts/products/get-setProducts-txdata.js
product type listing and product listing scripts improvements
* add validation for required data
* drop whitespace
* manually tested for this week's listing
=> feat: Product listing scripts improvements

test/fork/basic-functionality-tests.js, test/fork/cover-products.js
Issue: #1138 
- Add fork tests for the cover-products deployment
- Adept basic functionality tests with new changes and fix swap tests
=> test: CoverProducts fork tests

contracts/interfaces/ITokenController.sol, contracts/mocks/disposables/DisposableTokenController.sol, contracts/mocks/generic/PooledStakingGeneric.sol, contracts/mocks/generic/TokenControllerGeneric.sol, contracts/mocks/modules/TokenController/TCMockGovernance.sol, contracts/mocks/modules/TokenController/TCMockPooledStaking.sol, contracts/mocks/modules/TokenController/TCMockStakingNFT.sol, contracts/modules/token/TokenController.sol, test/integration/TokenController/setup.js, test/integration/TokenController/withdrawNXM.js, test/integration/setup.js, test/unit/TokenController/setup.js, test/unit/TokenController/withdrawNXM.js
Relates to: https://github.com/NexusMutual/smart-contracts/issues/1173
* add `TokenConroller.withdrawNxm`
I've split the tests in to 2 (unit and integration tests)
unit tests (mostly v1 stuff because we now deprecated v1 functionalities to add stake / generate rewards)
* governanceRewards
* v1CoverNotes
* v1PooledStakingStake
* v1PooledStakingRewards
* v1ClaimAssessmentRewards
integration tests:
* assessmentStake
* assessmentRewards
* stakingPoolStake
* stakingPoolRewards
* stakingPoolManagerRewards
* :thinking: = I don’t understand something, do you mind …
=> DRAFT: feat: Add batch TC.withdrawNXM

scripts/create2/deploy.js, scripts/create2/find-salt.js
Since we introduced an external library, we now need to add library linking steps in both find-salt and deploy create2 scripts.
* add libraries.json
* add library linking find-salt / deploy
Add validation checks on the scripts and tested manually for [StakingPool.sol find-salt](https://www.notion.so/nxmcommunity/Release-2-8-0-Staking-Pool-Fixes-Batch-Withdrawals-StakingViewer-f15e7b77eb44422883910ab12976d327?pvs=4#20385038979344e1bef08a22f996bc14)
=> feat: Add create2 library linking 

package-lock.json, scripts/staking-set-initial-pools-metadata.js, scripts/staking-update.js
Staking update script should be run as swap controller so we need to use aws kms signer.
Staking pools metadata was migrated to staking products so we needed a script for the tx data.
--
=> Add kms signer for `staking-update.js` and add initial metadata script

deployments/package-lock.json, deployments/package.json, deployments/src/addresses.json
Update deployments address.json of new addresses
* update StakingViewer address
* update version to 2.8.0
ran `npm run deployments:build` locally
=> chore: Update deployments StakingViewer and SwapOperator

deployments/package-lock.json
=> Update deployment package-lock version to 2.8.0

scripts/governance/get-decoded-action-data.js, scripts/governance/get-encoded-action-data.js, test/fork/execute-governance-proposal.js, test/fork/staking-pool-rewards.js
Add governance proposal scripts to be used for code release
Update docs here: https://www.notion.so/nxmcommunity/Contract-deployments-and-upgrade-fcc5bb988acd493cba9445112cf914ec
* add encode governance proposal action params
* add decode governance proposal action params
* add execute governance proposal script
Tested on [2.8.0 release](https://www.notion.so/nxmcommunity/Release-2-8-0-Staking-Pool-Fixes-Batch-Withdrawals-StakingViewer-f15e7b77eb44422883910ab12976d327)
* …
=> feat: Add governance proposal scripts

test-file
=> Add test-file

test-file
=> Feature: test second feature

test-file
=> Test release candidate

contracts/modules/capital/Pool.sol, test/fork/basic-functionality-tests.js, test/fork/long-term-limit-order.js, test/unit/Pool/getPoolValueInEth.js, test/unit/Pool/setSwapAssetAmount.js, test/unit/SwapOperator/closeOrder.js, test/unit/SwapOperator/placeOrder.js
=> audit: long term limit order fixes

package-lock.json, package.json
upgrade @nexusmutual/deployments to 2.9.0
=> chore: upgrade @nexusmutual/deployments to 2.9.0

deployments/package-lock.json, deployments/package.json, package-lock.json, package.json
update @nexusmutual/deployments to 2.10.0
=> chore: update @nexusmutual/deployments to 2.10.0

deployments/package-lock.json, deployments/package.json, package-lock.json, package.json
forgot to bump the version on the [previous PR](https://github.com/NexusMutual/smart-contracts/pull/1282)
=> chore: update version to 2.10.1

test/fork/basic-functionality-tests.js, test/fork/product-pricing-updates.js
This PR contains the fork test for the previous 3 PRs which are all merged in this one (#1294 #1298 #1299)
Added the fork test and changed basic functionality test.
=> test: fork test for product pricing updates

docs/TokenController.md
- [TokenController Contract Developer Documentation](#tokencontroller-contract-developer-documentation)
- [**Overview**](#overview)
- [**Key Concepts**](#key-concepts)
- [**Why TokenController Exists**](#why-tokencontroller-exists)
- [**NXM Token Utility \& Staking Impact**](#nxm-token-utility--staking-impact)
- [**Staking Pool Management**](#staking-pool-management)
- [**Locking and Unlocking Tokens**](#locking-and-unlocking-tokens)
- [**Rewards and Incentives**](#rewards-and-incentives)
- [**Mutative Functions**](#mutative-functions)
- [`operatorTransfer`](#operatortransfer)
- [`burnFrom`](#burnfrom)
- [`mint`](#mint)
- [**View Functions**](#view-functions)
- [`getTokenPrice`](#gettokenprice)
- [`totalBalanceOf`](#totalbalanceof)
- [**Integration Best …
=> docs: add TokenController contract docs

docs/Assessment.md
- [Assessment Contract Developer Documentation](#assessment-contract-developer-documentation)
- [Overview](#overview)
- [Key Concepts](#key-concepts)
- [Stake \& Voting Power](#stake--voting-power)
- [Stake Locking](#stake-locking)
- [Assessment \& Poll](#assessment--poll)
- [Voting Outcome](#voting-outcome)
- [ETH Deposits \& Claim Resolution](#eth-deposits--claim-resolution)
- [Reward Distribution](#reward-distribution)
- [Fraud Resolution](#fraud-resolution)
- [Configuration](#configuration)
- [Mutative Functions](#mutative-functions)
- [`stake(uint96 amount)`](#stakeuint96-amount)
- [`unstake(uint96 amount, address to)`](#unstakeuint96-amount-address-to)
- [`unstakeAllFor(address staker)`](#unstakeallforaddress-staker)
- [`withdrawRewards(address staker, uint104 …
=> docs: add Assessment contract docs

docs/IndividualClaims.md
- [IndividualClaims Contract Developer Documentation](#individualclaims-contract-developer-documentation)
- [**Overview**](#overview)
- [**Key Concepts**](#key-concepts)
- [**The Mutual and Claim Assessment Process**](#the-mutual-and-claim-assessment-process)
- [**Cover Segments**](#cover-segments)
- [**Claim Lifecycle**](#claim-lifecycle)
- [**Assessment Deposit and Rewards**](#assessment-deposit-and-rewards)
- [**Claim Status and Payout**](#claim-status-and-payout)
- [**Mutative Functions**](#mutative-functions)
- [`submitClaim`](#submitclaim)
- [**Integration Best Practices**](#integration-best-practices)
- [**What to Track Off-Chain**](#what-to-track-off-chain)
- [**Which Functions Should Be Polled?**](#which-functions-should-be-polled)
- [**Gas Considerations**](#gas-considerations) …
=> docs: add IndividualClaims contract docs

docs/user-flows/cover-buyer.md
- [Cover Buyer User Flow Documentation](#cover-buyer-user-flow-documentation)
- [Table of Contents](#table-of-contents)
- [Overview](#overview)
- [Key Concepts](#key-concepts)
- [Cover Length \& Grace Period](#cover-length--grace-period)
- [Cover Pricing \& Dynamic Adjustments](#cover-pricing--dynamic-adjustments)
- [Initial Price Ratio](#initial-price-ratio)
- [Target Price](#target-price)
- [Price Bump](#price-bump)
- [Price Decay](#price-decay)
- [How to Check Current Cover Pricing:](#how-to-check-current-cover-pricing)
- [Cover Router API \& Cover Buy Process](#cover-router-api--cover-buy-process)
- [Why Use the Cover Router API?](#why-use-the-cover-router-api)
- [Accepted Payment Assets](#accepted-payment-assets)
- [Membership Requirement](#membership-requirement)
- [Step-by-Step …
=> docs: add cover buyer user flows

contracts/interfaces/ICover.sol, contracts/modules/cover/Cover.sol, test/fork/cover-data-migration.js
Migration of _legacyCoverData, _legacyCoverSegments, _legacyCoverSegmentAllocations to the new _coverData and _poolAllocations
Fork tested full cover data migration and gas usage calculation.
=> feat: cover edits: cover data migration

contracts/interfaces/ICover.sol, contracts/mocks/generic/CoverGeneric.sol, contracts/modules/cover/Cover.sol, contracts/modules/staking/StakingPool.sol, contracts/modules/staking/StakingProducts.sol, test/integration/Cover/buyCover.js, test/integration/Cover/coverNFTDescriptor.js, test/integration/Cover/expireCover.js, test/integration/setup.js
Integration test fixes for Cover, and small contract fixes found during the testing.
=> test: cover integration test fixes

contracts/mocks/modules/Cover/COMockStakingPool.sol, contracts/mocks/modules/CoverViewer/CVMockCover.sol, test/unit/Cover/burnStake.js, test/unit/Cover/buyCover.js, test/unit/Cover/editCover.js, test/unit/Cover/helpers.js, test/unit/Cover/setup.js, test/unit/Cover/totalActiveCoverInAsset.js, test/unit/Cover/updateTotalActiveCoverAmount.js, test/unit/CoverProducts/setProductTypes.js, test/unit/CoverProducts/setup.js, test/unit/CoverViewer/views.js, test/unit/NexusViewer/setup.js
Fixing unit tests for Cover, CoverProducts, CoverViewer and NexusViewer. 
Includes fixes for edit cover tests that were skipped before.
=> test: cover unit test fixes

contracts/mocks/modules/Claims/CLMockAssessment.sol, contracts/mocks/modules/Claims/CLMockCoverProducts.sol, test/unit/IndividualClaims/getClaimsToDisplay.js, test/unit/IndividualClaims/helpers.js, test/unit/IndividualClaims/redeemClaimPayout.js, test/unit/IndividualClaims/setup.js, test/unit/IndividualClaims/submitClaim.js
=> [FF-ONLY] Tests: individual claims unit tests

contracts/mocks/generic/MulticallMock.sol, contracts/mocks/modules/StakingPool/SKMockCover.sol, contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/burnStake.js, test/unit/StakingPool/constructor.js, test/unit/StakingPool/depositTo.js, test/unit/StakingPool/helpers.js, test/unit/StakingPool/requestAllocation.js, test/unit/StakingPool/setPoolFee.js, test/unit/StakingPool/setup.js, test/unit/StakingPool/withdraw.js, test/unit/StakingProducts/createStakingPool.js, test/unit/StakingProducts/helpers.js, test/unit/StakingProducts/setup.js
Fixed StakingPool and StakingProducts unit tests to pass after cover edit changes.
=> [FF-ONLY] Tests: fix StakingPool and StakingProducts unit tests

contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/extendDeposit.js
Explicitly update the manager's fee on `extendDeposit`
=> Fix: manager deposit

contracts/modules/cover/LimitOrders.sol, test/integration/LimitOrders/executeOrder.js, test/integration/setup.js
=> fix: add `whitelistSelf` function to LimitOrders contract

contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/extendDeposit.js
The manager deposit on the target tranche didn't account for new reward shares.
Tests added.
=> fix: manager deposit fix fix

contracts/interfaces/ILimitOrders.sol, contracts/modules/cover/LimitOrders.sol, test/integration/LimitOrders/executeOrder.js, test/integration/setup.js, test/unit/LimitOrders/cancelOrder.js, test/unit/LimitOrders/getOrderId.js, test/utils/buyCover.js
=> fix: limit orders audit fixes

contracts/interfaces/IStakingPool.sol, contracts/modules/staking/StakingPool.sol, test/unit/StakingPool/burnStake.js, test/unit/StakingPool/depositTo.js, test/unit/StakingPool/extendDeposit.js, test/unit/StakingPool/processExpirations.js
Add more staking events to ease the development of the dune dashboards.
Added the corresponding tests for all functions that emit these events.
=> feat: add more StakingPool events

contracts/interfaces/IIndividualClaims.sol
=> chore: remove comments

hardhat-config/solidity.js, lib/constants.js, package-lock.json, package.json, test/fork/basic-functionality-tests.js, test/fork/cover-data-migration.js, test/fork/cover-edits.js, test/fork/evm.js, test/fork/limit-orders.js, test/fork/load-contracts.js, test/fork/march2025-release.js, test/fork/setup.js, test/fork/utils.js, test/utils/membership.js
Fixing basic functionality fork tests and added base for the cover edits fork test. 
=> test: march release fork tests

scripts/migrate-cover-data.js
Script to migrate all cover data and pool allocations
=> chore: migrate cover data script

contracts/interfaces/ICover.sol, contracts/interfaces/ILimitOrders.sol, contracts/modules/cover/Cover.sol, contracts/modules/cover/LimitOrders.sol, test/unit/Cover/buyCover.js, test/unit/Cover/editCover.js, test/unit/Cover/helpers.js
=> fix: audit patch findings

.github/config/conventional-bump-setup.js
add missing conventional-bump-setup.js
=> fix: add missing conventional-bump-setup.js

.github/workflows/release-next.yml
add root package.json rc version bump
=> fix: add root package.json rc version bump

contracts/interfaces/IRamm.sol, contracts/modules/capital/Ramm.sol, test/unit/Ramm/swap.js
=> chore: add vote lock check

contracts/abstract/RegistryAware.sol, contracts/interfaces/IAssessment.sol, contracts/interfaces/IClaims.sol, contracts/interfaces/IPool.sol, contracts/mocks/common/PoolMock.sol, contracts/mocks/generic/PoolGeneric.sol, contracts/modules/assessment/Assessment.sol, contracts/modules/assessment/Claims.sol, contracts/modules/capital/Pool.sol
=> feat: permissioned assessments - live vote tally

contracts/interfaces/IGovernor.sol, contracts/mocks/generic/RegistryGeneric.sol, contracts/mocks/generic/TokenControllerGeneric.sol, contracts/mocks/modules/Governor/GVMockRegistry.sol, contracts/mocks/modules/Governor/GVMockTokenController.sol, contracts/modules/governance/Governor.sol, lib/constants.js, test/unit/Governor/cancel.js, test/unit/Governor/execute.js, test/unit/Governor/getProposal.js, test/unit/Governor/propose.js, test/unit/Governor/proposeAdvisoryBoardSwap.js, test/unit/Governor/setup.js, test/unit/Governor/vote.js
=> test: governor unit tests

MIGRATION.md, contracts/interfaces/ITokenControllerErrors.sol, contracts/mocks/modules/Governor/GVMockTokenController.sol, contracts/modules/assessment/Claims.sol, contracts/modules/governance/Governor.sol, contracts/modules/governance/Registry.sol, contracts/modules/legacy/LegacyMemberRoles.sol, contracts/modules/token/TokenController.sol, test/unit/Governor/execute.js, test/unit/Governor/getProposal.js, test/unit/Governor/proposeAdvisoryBoardSwap.js, test/unit/Governor/setup.js
=> feat: v3 solidity todos

contracts/modules/legacy/LegacyMemberRoles.sol
=> fix: retreive eth member roles and ab migration

contracts/modules/assessment/Claims.sol, test/unit/Claims/submitClaim.js
Store all claims of a member in an array.
Test added.
=> feat: get member claims

MIGRATION.md, test/fork/assessment-claims.js, test/fork/v3.js
update v3 fork test and MIGRATION.md
=> test: update v3 fork test and MIGRATION.md

MIGRATION.md, contracts/interfaces/IClaims.sol, contracts/mocks/modules/Assessment/ASMockClaims.sol, contracts/modules/assessment/Claims.sol, test/fork/assessment-claims.js, test/fork/basic-functionality-tests.js, test/fork/legacy-assessment.js, test/fork/utils.js, test/fork/v3.js, test/unit/Claims/redeemClaimPayout.js, test/unit/Claims/retrieveDeposit.js, test/unit/Claims/submitClaim.js
Fixes fork tests. They're currently passing. Next step is to adapt them to the migration plan: reorder, run the transactions via safe multisig, etc.
=> feat: claims update and fork tests cleanup

scripts/create-tenderly-vnet.js, scripts/create1/deploy.js, scripts/create1/deply.js, scripts/create1/find-address.js, scripts/create2/deploy.js, scripts/create2/find-salt.js, scripts/create2/get-signer.js
=> chore: deployment scripts create1 and create2 

test/fork/assessment-claims.js, test/fork/basic-functionality-tests.js
=> test: bft claims and assessments
