NexusMutual/smart-contracts

contracts/ClaimsReward.sol
contracts/TokenController.sol
contracts/TokenFunctions.sol
package-lock.json
test/09_ClaimReward.test.js
test/16_burnStakerStake.test.js
test/18_ClaimAssessment.test.js
test/22_UnlockFixes.test.js

Proposals passed #56, 57. 58.
What this includes:
Limiting functionality of lock, increase lock amount, extend lock for claims Assessment only. We have separate functions for RA and CN
Limiting unlock to internal functions only.
Addition of unlocking of CA tokens in function claimAllPendingRewards.
Fixing up of all spoiled records like Hugh's
Disallow deposited tokens from being unlocked. This also solves the problem of expiring covers after claim has been submitted.
Correction of lock time for cover notes. Initially current time was being added twice.

Fix issue 181 unlock bug

---

contracts/mocks/Assessment/ASMockIndividualClaims.sol
contracts/mocks/Assessment/ASMockYieldTokenIncidents.sol
contracts/modules/v2/Assessment.sol
contracts/modules/v2/CoverMigrator.sol
contracts/modules/v2/IndividualClaims.sol
contracts/modules/v2/YieldTokenIncidents.sol
test/unit/Assessment/index.js
test/unit/Assessment/initialize.js
test/unit/Assessment/setup.js
test/unit/CoverMigrator/index.js
test/unit/CoverMigrator/setup.js
test/unit/CoverMigrator/submitClaim.js
test/unit/IndividualClaims/index.js
test/unit/IndividualClaims/initialize.js
test/unit/IndividualClaims/setup.js
test/unit/YieldTokenIncidents/index.js
test/unit/YieldTokenIncidents/initialize.js
test/unit/YieldTokenIncidents/setup.js
test/unit/index.js

Also fixes CoverMigrator units tests and prevents calling intitializers
for the second time which could allow anyone to reset the config back to
the initial state if it were to be changed through governance.

Add pause modifiers to functions in assessment contracts

---

contracts/modules/cover/Cover.sol

Not sure if it was working using the previous declaration, but I assume
the event was emitted before the return value was initialized which
could have lead to stakingPoolAddress to be the 0 address. This should
make it obvious that never happens.

Make sure stakingPoolAddress is emitted

---

contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverUtilsLib.sol
test/integration/setup.js
test/unit/Cover/setup.js

It should be calculated using the proxy address, not the implementation
since it is run in the constructor of Cover.sol which is not aware of
its proxy address without explicitly passing it offchain.

Fix proxy code hash used in staking pools addresses

---

contracts/interfaces/IStakingPool.sol
contracts/libraries/Math.sol
contracts/libraries/UncheckedMath.sol
contracts/mocks/Cover/CoverMockStakingPool.sol
contracts/modules/cover/Cover.sol
contracts/modules/staking/StakingPool.sol

Implement allocate and deallocate

---

contracts/modules/cover/CoverUtilsLib.sol
contracts/modules/staking/StakingPool.sol

Made some code changes to silence 4 warnings. 3 of which are only temporariy until StakingPool functions are finished.
- Changed calculateProxyCodeHash() from view to pure. 
- Added placeholder code to silence unused parameter in StakingPool.tokenURI()
- Added sstore to StakingPool.removeProduct() & addProduct() to avoid warning that function should be `view`
Fixes #271 
- Chore
- `npx hardhat clean && npm run compile`

chore: silence unused variable warnings and function visibility.

---

contracts/interfaces/ICover.sol
contracts/interfaces/IIndividualClaims.sol
contracts/interfaces/IYieldTokenIncidents.sol
contracts/mocks/Claims/CLMockCover.sol
contracts/mocks/Incidents/ICMockCover.sol
contracts/modules/assessment/IndividualClaims.sol
contracts/modules/assessment/YieldTokenIncidents.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverUtilsLib.sol
contracts/modules/cover/CoverViewer.sol
test/unit/Assessment/helpers.js
test/unit/Cover/buyCover.js
test/unit/Cover/editCover.js
test/unit/Cover/expireCover.js
test/unit/Cover/helpers.js
test/unit/Cover/performStakeBurn.js
test/unit/Cover/totalActiveCoverInAsset.js
test/unit/IndividualClaims/helpers.js
test/unit/IndividualClaims/submitClaim.js
test/unit/YieldTokenIncidents/helpers.js

Description
Fixes Issue: https://github.com/NexusMutual/smart-contracts/issues/355
Rename for less confusion.
Semantically, a payoutAsset is the same as a coverAsset so they should converge on the same name.
Type of change
Chore 
How Has This Been Tested?
All curent tests running again.
```npm run test-unit```
See the added test in the PR.
npm run test-unit

rename payoutAsset -> coverAsset

---

contracts/interfaces/ICoverNFT.sol
contracts/interfaces/IERC721Mock.sol
contracts/mocks/Claims/CLMockCover.sol
contracts/mocks/Claims/CLMockUnknownNFT.sol
contracts/mocks/Incidents/ICMockCover.sol
contracts/mocks/Incidents/ICMockUnknownNFT.sol
contracts/mocks/MemberRoles/MRMockCover.sol
contracts/mocks/Tokens/ERC721Mock.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverNFT.sol
contracts/modules/cover/CoverUtilsLib.sol
test/unit/MemberRoles/switchMembershipAndAssets.js

Fixes #354
Changed all `safeMint()` function calls to use `mint()` instead. 
-  Chore 
I didn't add any further tests, as I didn't see any yet for the NFTs.
`npm run test`

chore: replace safeMint() calls with regular mint()

---

contracts/mocks/Claims/CLMockUnknownNFT.sol
contracts/mocks/Cover/CoverMockNFT.sol
contracts/mocks/Cover/CoverMockStakingPool.sol
contracts/mocks/Incidents/ICMockUnknownNFT.sol
contracts/mocks/MemberRoles/MRMockCoverNFT.sol
contracts/mocks/MemberRoles/MRMockStkaingPool.sol
contracts/mocks/Tokens/ERC721Mock.sol
contracts/mocks/integration/IntegrationMockStakingPool.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverNFT.sol
contracts/modules/cover/CoverViewer.sol
contracts/modules/staking/StakingPool.sol
package-lock.json
package.json
test/unit/Cover/coverNFT.js
test/unit/Cover/index.js
test/unit/Cover/setup.js
test/unit/MemberRoles/switchMembershipAndAssets.js

resolves #295 
This PR replaces the OZ 721 implementation with solmates 721 implementation. 
No further tests were added.

Replace OZ base NFT with solmate in CoverNFT

---

contracts/mocks/CoverViewer/CoverViewerMockCover.sol
contracts/modules/cover/CoverViewer.sol
test/unit/CoverViewer/index.js
test/unit/CoverViewer/setup.js
test/unit/CoverViewer/views.js
test/unit/index.js

Fixes Issue: https://github.com/NexusMutual/smart-contracts/issues/364
This is needed for displaying all cover segments in the UI.
It's easier to add it in the CoverViewer.sol to not bloat Cover.sol size so a function is added there for returning a list of CoverSegment items.
Added test for CoverViewer
```npm run test-unit```

Feat: Add cover segments view

---

contracts/interfaces/IPriceFeedOracle.sol
contracts/modules/capital/Pool.sol
contracts/modules/capital/PriceFeedOracle.sol
test/unit/CowOperator/setup.js
test/unit/Pool/addAsset.js
test/unit/Pool/getPoolValueInEth.js
test/unit/Pool/index.js
test/unit/Pool/removeAsset.js
test/unit/Pool/setSwapDetailsLastSwapTime.js
test/unit/Pool/setup.js
test/unit/Pool/transferAsset.js
test/unit/Pool/transferAssetToSwapOperator.js
test/unit/Pool/updateParameters.js
test/unit/Pool/upgradeCapitalPool.js

Fixes issue: https://github.com/NexusMutual/smart-contracts/issues/314
We want to prevent addition of assets don't have a registered oracle.
This prevents any issue with pool value calculations that may lock the system.
Add a require to the addAsset function in Pool.sol
Upgrade all tests that interact with addAsset to now have a oracle available.
`npm run test-unit`

Check that when an asset is added to the pool it has an oracle

---

contracts/modules/cover/Cover.sol
contracts/modules/staking/StakingPool.sol
test/integration/setup.js
test/unit/Cover/index.js
test/unit/Cover/initialize.js

Fixes issue: https://github.com/NexusMutual/smart-contracts/issues/350
Add an initialize() function with hardcoded parameters for StakingPool.sol since it's a proxy.
Add the initialize() function.
Change decimals for globalRewardsRatio to 4 therefore denominator is 10000. 
There was a discrepancy between Cover.sol and StakingPool.sol (had 2 decimals).
Added unit test.
`npm run test-unit`

Feat: Add initialize function to Cover.sol

---

test/unit/Assessment/withdrawRewardsTo.js

Closes #337  Assessment unit tests
This PR adds more unit tests for the `withdrawRewardsTo()` function. 
More tests were added in `test/unit/Assessment/withdrawRewardsTo.js`

Feature/Add unit tests for withdrawRewardsTo

---

contracts/modules/staking/StakingPool.sol

Fixes #299
When the pool is new, the function was always skipping the updates, never updating any value. Because of this early exit the function was never updating anything.
The new implementation will stil exit early without updating anything if a forced update was not requested (`updateUntilCurrentTimestamp = true`). A force update should be requested if the function calling `updateTranches` changes the share supply. If the share supply is not being changed - we should be fine skipping the update i.e. avoid any writes.
I'm not entirely sure there aren't any edge cases that I didn't account for. Please review carefully.
No tests present for staking at the moment.
* :cake: = Nice to have but not …

Fix: update tranches not performing any updates

---

contracts/interfaces/ICover.sol
contracts/modules/assessment/YieldTokenIncidents.sol
contracts/modules/cover/CoverViewer.sol
scripts/deploy/deploy.js
test/integration/setup.js
test/unit/Cover/addProducts.js
test/unit/Cover/editProducts.js
test/unit/Cover/setup.js

Fixes issue https://github.com/NexusMutual/smart-contracts/issues/415.
We agreed that productAsset is quite confusing in this context, and decided to make it more specific. 
Ran existing tests.

Chore: Rename productAddress in ytcUnderlyingAsset in Product struct

---

contracts/interfaces/ICover.sol
contracts/mocks/Claims/CLMockCover.sol
contracts/mocks/Incidents/ICMockCover.sol
contracts/modules/assessment/IndividualClaims.sol
contracts/modules/assessment/YieldTokenIncidents.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverUtilsLib.sol
contracts/modules/cover/CoverViewer.sol
test/unit/Cover/buyCover.js
test/unit/Cover/editCover.js
test/unit/Cover/helpers.js
test/unit/Cover/performStakeBurn.js
test/unit/CoverViewer/views.js
test/unit/IndividualClaims/getClaimsCount.js
test/unit/IndividualClaims/getClaimsToDisplay.js
test/unit/IndividualClaims/helpers.js
test/unit/IndividualClaims/redeemClaimPayout.js
test/unit/IndividualClaims/submitClaim.js
test/unit/YieldTokenIncidents/redeemPayout.js

Resolves #287 
This PR adds the ability to edit gracePeriodInDays. To do this `gracePeriodInDays` was added to the CoverSegments struct. Deallocation and claims should now use the grace period from the cover segment.  Allocations should use the product level grace period.

Feature: edit product grace period

---

contracts/interfaces/IAssessment.sol
contracts/modules/assessment/Assessment.sol
test/unit/Assessment/castVotes.js
test/unit/Assessment/stake.js
test/unit/Assessment/unstake.js
test/unit/Assessment/withdrawRewards.js
test/unit/Assessment/withdrawRewardsTo.js

Fixes #424 
Adds events to the `stake()`, `unstake()`,  `withdrawRewards()`,  `withdrawRewardsTo()` and `castVote()` methods.
Used the events already defined in `contracts/interfaces/IAssessment.sol`. The only event that was updated is the `VoteCast` event to include the assessment id as a parameter.
Unit tests for the corresponding events were introduced in:
- `test/unit/Assessment/stake.js`
- `test/unit/Assessment/unstake.js`
- `test/unit/Assessment/withdrawRewards.js`
- `test/unit/Assessment/withdrawRewardsTo.js`
- `test/unit/Assessment/castVotes.js`
* …

Feature/ Add Assessment missing function events

---

test/unit/Assessment/castVotes.js
test/unit/Assessment/setup.js
test/unit/Assessment/startAssessment.js

Closes #430
Adds new unit tests for `startAssessment` and `castVotes`.  Implemented the list of test cases from the issue, with the following exceptions:
- `Should emit an event on each vote` was already implemented in another PR.
- `Should correctly extend the end date up to 1 day maximum if polls ends in less than 24 hours` was already tested as part of one of the implemented tests.
New tests were added in `test/unit/Assessment/startAssessment.js` and `test/unit/Assessment/castVotes.js`
* :thinking: = I don’t understand something, do you mind giving me …

Test/ Add Assessment startAssessment and castVotes unit tests

---

contracts/modules/assessment/Assessment.sol
test/unit/Assessment/processFraud.js
test/unit/Assessment/submitFraud.js

Closes #431 
Adds new unit tests for `submitFraud` and `processFraud`. Implemented the list of test cases from the issue.
As part of the testing of `submitFraud` the state variable `fraudResolution` from the `Assessment` contract was changed from `internal` to `public`. This allows verifying the stored fraud merkle tree roots, which should also facilitate getting the root index of the array that needs to be passed as a parameter in the `processFraud` method.
New tests were added in `test/unit/Assessment/submitFraud.js` and `test/unit/Assessment/processFraud.js`
* :hammer: = I believe this should be …

Test/ Add Assessment submitFraud and processFraud unit tests

---

contracts/interfaces/ICover.sol
contracts/mocks/Claims/CLMockCover.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverUtilsLib.sol
test/unit/CoverMigrator/submitClaim.js

Solves issue: https://github.com/NexusMutual/smart-contracts/issues/437
There's no easy way to know what's the new cover id of the cover you just migrated. This is necessary in the UI to know what use as a parameter for claim submission.
This PR adds an event for each migrated cover.
1 new event type CoverMigrated and an emit call.
We do not have tests for `migrateCovers`. We can add a verification for the event when we get there.
We can add the check when those tests are written. 
* :thinking: = I don’t understand something, do you mind giving me more …

Fix: Add event for migrateCover

---

contracts/mocks/Claims/CLMockPool.sol
contracts/mocks/Claims/CLMockPoolEtherRejecter.sol
contracts/modules/assessment/IndividualClaims.sol
test/unit/IndividualClaims/constructor.js
test/unit/IndividualClaims/index.js
test/unit/IndividualClaims/initialize.js
test/unit/IndividualClaims/redeemClaimPayout.js
test/unit/IndividualClaims/setup.js
test/unit/IndividualClaims/submitClaim.js

Closes #433
Adds new unit tests for the constructor, initialize, submitClaim and redeemClaimPayout. Implemented the list of test cases from the issue. nxm and coverNFT were changed to public in `IndividualClaims` contract to be able to fetch it for testing. 
A new mock `CLMockPoolEtherRejecter` was added extending the one that was used in the setup to have available the necessary pool methods used inside `submitClaim` but also to revert on`fallback/receive` to test that.
New tests were added in `test/unit/IndividualClaims/initialize.js`,`test/unit/IndividualClaims/constructor.js`, `test/unit/IndividualClaims/submitClaim.js` and `test/unit/IndividualClaims/redeemClaimPayout.js`
* :cake: = Nice to have …

Test/ Add IndividualClaims tests

---

test/unit/Cover/buyCover.js
test/unit/Cover/editCover.js
test/unit/Cover/helpers.js
test/unit/Cover/performStakeBurn.js

Partial implementation of #268
Adds new revert unit tests for `buyCover`. Implemented some of the listed test cases, especially the reverts one.
I couldn't find a way to test `Cover: Product not initialized`, it seems that when a product is listed it also initializes the parameters so I couldn't reproduce a state of listed but with `initialPriceRatio = 0` as the code is checking.
Also, I removed the usage of `bnEqual` in the `buyCover` tests as it triggers a warning `Warning: Use Hardhat Chai Matchers instead of bnEqual: https://hardhat.org/hardhat-chai-matchers/docs/overview#big-numbers`
New tests were added in `test/unit/Cover/buyCover.js`
* :bulb: = …

Test/ Add buyCover revert unit tests

---

contracts/modules/capital/MCR.sol
contracts/modules/capital/Pool.sol
contracts/modules/cover/Cover.sol
contracts/modules/governance/Governance.sol

Fixes part of the items in https://github.com/NexusMutual/smart-contracts/issues/324
- [Governance.sol#L463](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/governance/Governance.sol#L463): totalRewar -> totalReward
- [Cover.sol#L648](https://github.com/NexusMutual/smart-contracts/blob/14a7ed6f5b6df877a2cb7eb9fd390c9cb216ccb2/contracts/modules/cover/Cover.sol#L648): initialProuctTypesCount -> initialProductTypesCount
Made sure existing tests run.
* :thinking: = I don’t understand something, do …

Chore: Design comments

---

test/unit/Cover/createStakingPool.js
test/unit/Cover/helpers.js
test/unit/Cover/performStakeBurn.js

Closes #274 
Adds new unit tests for `createStakingPool` and `performStakeBurn`. Implemented the list of test cases from the issue.
New tests were added in `test/unit/Cover/createStakingPool.js` and `test/unit/Cover/performStakeBurn.js`

Test: Add createStakingPool and performStakeBurn unit tests

---

test/unit/Cover/commitActiveCoverAmounts.js
test/unit/Cover/enableActiveCoverAmountTracking.js
test/unit/Cover/expireCover.js
test/unit/Cover/index.js

Relates to #278 
Adds new unit tests for `enableActiveCoverAmountTracking`, `commitActiveCoverAmounts`, and `expireCover`. Implemented the list of test cases from the issue, except for the following ones that are going to be submitted in another PR as integration tests:
- `Should expire a cover that had a claim paid out fully`
- `Should expire a cover that had partial claim paid out`
- `Should expire a cover that had rejected claim`
New tests were added in `test/unit/Cover/enableActiveCoverAmountTracking.js`, `test/unit/Cover/commitActiveCoverAmounts.js` and `test/unit/Cover/expireCover.js`
* :hammer: …

Test: Add active cover amount tracking unit tests

---

contracts/mocks/StakingPool/SPMockCover.sol
test/unit/StakingPool/setProducts.js
test/unit/StakingPool/setup.js

closes #460 
This PR refactors the StakingPool.setProducts unit tests.
`test/unit/StakingPool/setProducts.js`

Chore: staking pool management tests stylistic changes

---

contracts/modules/cover/CoverNFT.sol
test/unit/Cover/coverNFT.js

Closes #464
Changed `CoverNFT` to avoid `address(0)` being set as a new operator and added some tests for `changeOperator`. 

Test/ add missing tests for coverNFT

---

test/unit/SwapOperator/closeOrder.js
test/unit/SwapOperator/helpers.js
test/unit/SwapOperator/index.js
test/unit/SwapOperator/placeOrder.js
test/unit/SwapOperator/setup.js

Closes #390
Refactored out some common constants between `placeOrder` and `closeOrder`. Also tried to flatten the nesting of `describe` blocks without losing too much context for each unit test.

Test/ Refactor of swap operator tests

---

contracts/interfaces/ICover.sol
contracts/mocks/StakingPool/SPMockCover.sol
contracts/modules/staking/StakingPool.sol
contracts/modules/staking/StakingTypesLib.sol
test/integration/Cover/expireCover.js
test/integration/IndividualClaims/submitClaim.js
test/integration/YieldTokenIncidents/submitClaim.js
test/unit/StakingPool/setProducts.js

Fixes #448
Previously we weren't reading the capacities and allocations for all the tranches when allocating stake for a particular cover which could result in situations where the allocations could happen above the target weight.
This PR ensures that we read all active tranches (capacity and allocations) in order to calculate the actual weight of the product.
Currently there are no tests and there's another issue that will modify the allocateStake function. The tests for the next PR should cover this one as well.
* :thinking: = I don’t understand …

Fix: check weight on all tranches

---

contracts/interfaces/IStakingPool.sol
contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/setProducts.js

Closes #454  
This PR changes the `stakingPool.setProducts()` function so the target weight of a product can be lowered, even if the pool has exceeded it's max effective weight. 
A function is also added, so that any user can recalculate the effective weights of the pool.
There isn't much to test until the burn functionality is implemented. Will add more on that PR.

Feature: Allow managers to lower targetWeights even if effectiveWeight is exceeded

---

hardhat.config.js/tasks.js

The typechain task just calls compile task ([link](https://github.com/dethcrypto/TypeChain/blob/8c056bfd41635a8bee8e95cbea276533fd98c105/packages/hardhat/src/index.ts#L113)). In june they added prop noTypechain to be equal to noTypechain argument or dontOverrideCompile. So from there if the dontOverrideCompile is set to false it will never generate anything with typechain
Issue: #497 
_**EDIT**_
HACK: Overriding `dontOverrideCompile` in typechain task and then calling the `runSupper`. This way it will generate a types folder with all files.
for results just run command:
`npm run typechain` or `hardhat typechain`
* :bulb: = Suggestion or a comment based on …

BUGFIX: Typechain not  generating anything

---

contracts/interfaces/IIndividualClaims.sol

We need to be able to filter the `ClaimSubmitted` events by user and cover. The params need to be indexed for the event to be filterable (see error: `Cannot filter non-indexed parameters; must be null`)
Closes #514 
- indexed `user` and `coverId` params
N/A

Feat: Index user and coverId params of ClaimSubmitted event for filtering

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/depositTo.js
test/unit/StakingPool/index.js
test/unit/StakingPool/updateTranches.js

This PR fixes two issues related to expiring tranches from the `updateTranches` method.
1. Expired tranche is not being expired: In a new pool, if a tranche has a deposit and then no other activity until after the tranche end time passes, when calling `updateTranches` that tranche was not being expired. The reason is that `firstActiveBucketId` is `0` so the first active bucket and tranche were being assigned to the `currentBucketId` and `currentTrancheId`, so then the `while` condition was `false` and the tranche was not expired.
2. Division by zero error: If multiple expired tranches are being expired in a `updateTranches` call, if all stakeShares were burned before the last expiring tranche, a division by zero error was being thrown. …

Fix: updateTranches not expiring tranches

---

contracts/modules/assessment/Assessment.sol
contracts/modules/assessment/IndividualClaims.sol
contracts/modules/assessment/YieldTokenIncidents.sol
contracts/modules/cover/CoverUtilsLib.sol

Closes #419 
This PR increases the size of uints, when multiplying two uints that are smaller than 256 bits, to avoid overflows. 
Did not add any further tests

Fix: Cast small uints to 256 bits before multiplying

---

contracts/interfaces/IAssessment.sol
contracts/modules/assessment/Assessment.sol
test/integration/Cover/expireCover.js
test/integration/IndividualClaims/submitClaim.js
test/integration/YieldTokenIncidents/submitClaim.js
test/unit/Assessment/castVotes.js
test/unit/Assessment/getPoll.js
test/unit/Assessment/getRewards.js
test/unit/Assessment/getVoteCountOfAssessor.js
test/unit/Assessment/helpers.js
test/unit/Assessment/processFraud.js
test/unit/Assessment/unstake.js
test/unit/Assessment/withdrawRewards.js
test/unit/Assessment/withdrawRewardsTo.js

No data is preserved during claim assessment, every value of the input in the form is lost and can not be used in the future (like showing reasons of the denial)
Closing issue: #494 
Expanding the `castVote` method on the Assassment.sol with ipfsAssessmentDataHash and emitting the hash in the `VoteCast` event
All existing tests modified with the changes made to the contract.

Feature: assessment data ipfs hash

---

contracts/modules/assessment/YieldTokenIncidents.sol
test/integration/Cover/expireCover.js
test/integration/YieldTokenIncidents/submitClaim.js
test/unit/Assessment/startAssessment.js
test/unit/Assessment/updateUintParameters.js
test/unit/IndividualClaims/updateUintParameters.js
test/unit/YieldTokenIncidents/getIncidentsCount.js
test/unit/YieldTokenIncidents/getIncidentsToDisplay.js
test/unit/YieldTokenIncidents/redeemPayout.js
test/unit/YieldTokenIncidents/submitIncident.js
test/unit/YieldTokenIncidents/updateUintParameters.js

Closes issue https://github.com/NexusMutual/smart-contracts/issues/446.
For better security, no one single AB member should be able to have special powers, but we should leverage the governance system with an AB only proposal category for submitIncident(). 
Note that the only other operation that is AB-only is add/edit/remove products and product types. To decrease friction, we should leave it as is, but have an alert setup for these actions.
Updated all existing tests. There already is a test for the modifier.
* :thinking: = I don’t understand something, …

Fix: Replace onlyAdvisoryBoard with onlyGovernance for submitIncident()

---

contracts/modules/cover/Cover.sol
test/unit/Cover/buyCover.js

The variable `coverSegmentAllocations` is storing the allocation to the incorrect `coverId`.  The struct `AllocationRequest` initializes the coverId to `0` and then is not updated so all allocation ended up being stored for that coverId.
Updates the `allocationRequest.coverId` so it uses the correct `coverId`.
A new test was added in `test/unit/Cover/buyCover.js`. The test fails without the fix.

Fix:  Use correct coverId for request allocation in buyCover

---

contracts/modules/staking/StakingPool.sol

An underflow issue in the `StakingPool.getActiveAllocations` function was hit during pricing tests.
- The issue was caused by the wrong tranche id passed when calling `updateExpiringCoverAmounts` from `allocate` hence having tranches misaligned (stored active cover vs expirations in buckets). This led to `getActiveAllocations` attempting to expire the tranche that dind't have the allocated capacity.
- This PR also fixes a todo where the indexes seemed wrong inside `getActiveAllocationsWithoutCover` function.
- Additionally I'm including the commit that exposed a few pricing functions as pure functions. This does not change the logic itself.
The test for this is on the `test/pricing-unit-tests` branch - PR #543 (and it passed) but I'm submitting the fixes separately to avoid any blockers …

Fix: staking pool expirations buckets underflow

---

contracts/interfaces/IStakingPool.sol
contracts/mocks/Cover/CoverMockStakingPool.sol
contracts/modules/cover/CoverUtilsLib.sol
contracts/modules/legacy/LegacyPooledStaking.sol
contracts/modules/staking/StakingPool.sol
contracts/modules/token/TokenController.sol
test/integration/Cover/createStakingPool.js
test/integration/Cover/expireCover.js
test/integration/IndividualClaims/submitClaim.js
test/integration/YieldTokenIncidents/submitClaim.js
test/unit/StakingPool/depositTo.js
test/unit/StakingPool/extendDeposit.js
test/unit/StakingPool/processExpirations.js
test/unit/StakingPool/setPoolFee.js
test/unit/StakingPool/setProducts.js

The array parameters unnecessary complicate the logic, increasee the code size and if the functions will be mostly used for a single deposit - they'll consume more gas.
Issue: #557 
This PR simplifies this logic and makes the function act on a single deposit. There's also the new `multicall` function which adds support for performing multiple operations in a single tx if there's a need for that at any point.
Fixed all the tests that started to fail because of it. There's a single test that used 2 deposit in a single tx and I've used multicall for that. 
* …

Feature: staking pool depositTo/withdraw/extend without arrays

---

contracts/interfaces/IStakingPool.sol
contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/helpers.js
test/unit/StakingPool/initialize.js
test/unit/StakingPool/setProducts.js

Given "next price" (formerly "last price") is not actually the price that will be used for the next cover buy it was a source of confusion.
Renamed to `nextPrice` and `nextPriceUpdateTime` to `bumpedPrice` and `bumpedPriceUpdateTime`
Functionality is not affected. A search and replace was performed on tests and everything should pass.

Chore: rename next price to bumped price

---

contracts/modules/capital/Pool.sol
lib/constants.js
test/integration/Master/master.js
test/unit/Pool/addAsset.js
test/unit/Pool/buyNXM.js
test/unit/Pool/calculateEthForNXM.js
test/unit/Pool/calculateNXMForEth.js
test/unit/Pool/calculateTokenSpotPrice.js
test/unit/Pool/getMCRRatio.js
test/unit/Pool/getPoolValueInEth.js
test/unit/Pool/getTokenPrice.js
test/unit/Pool/getters.js
test/unit/Pool/removeAsset.js
test/unit/Pool/sellNXM.js
test/unit/Pool/sellNXMTokens.js
test/unit/Pool/sendPayout.js
test/unit/Pool/setSwapDetailsLastSwapTime.js
test/unit/Pool/setSwapValue.js
test/unit/Pool/setup.js
test/unit/Pool/transferAsset.js
test/unit/Pool/transferAssetToSwapOperator.js
test/unit/Pool/updateParameters.js
test/unit/Pool/upgradeCapitalPool.js
test/unit/StakingPool/depositTo.js
test/utils/errors.js
test/utils/index.js
test/utils/token-price.js

No ticket number for this one.
I noticed the pool unit tests were still using truffle/web3 so I updated them before writing more tests in the upgrade-capital-pool PR
No tests were added

Feature: Update all capital pool unit tests to use ethers instead of truffle/web3

---

contracts/modules/cover/Cover.sol
test/integration/MemberRoles/switchMembershipAndAssets.js
test/integration/YieldTokenIncidents/submitClaim.js
test/integration/utils/staking.js
test/unit/Cover/buyCover.js

Closes issue https://github.com/NexusMutual/smart-contracts/issues/594
Check the total allocated cover amount is >= the requested cover amount. Use `>=` and not `==` as suggested in the audit report because the allocated cover amount is converted from asset to NXM and back to asset (using `divCeil` and `roundUp`), making the amount input to `buyCover` function act as a "min amount" in fact.
Updated existing tests.

Bug: Ensure the allocated cover amount is >= the requested cover amount

---

contracts/interfaces/IStakingPool.sol
contracts/mocks/TokenControllerMock.sol
contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/depositTo.js
test/unit/StakingPool/extendDeposit.js
test/unit/StakingPool/helpers.js
test/unit/StakingPool/index.js
test/unit/StakingPool/processExpirations.js
test/unit/StakingPool/setPoolFee.js
test/unit/StakingPool/setup.js
test/unit/StakingPool/withdraw.js

Closes #491 
Added `Withdraw` event to `StakingPool` contract and `withdrawNXMStakeAndRewards` method to `TokenControllerMock`. Also in setup update `master` address for tokenController.
Added unit tests to `StakingPool/withdraw.js`.

Test: withdraw unit tests

---

contracts/mocks/Cover/CoverMockStakingPool.sol
contracts/modules/cover/Cover.sol
test/unit/Cover/buyCover.js

closes #560 
This PR addresses a bug where the ETH premium wasn't being sent to the capital pool when buying a cover with ETH as payment asset.
Added checks that ETH is transferred in already existing unit tests `unit/buyCover.js`

Fix: 5.1.3 Premium never sent to Pool

---

contracts/interfaces/IMemberRoles.sol
contracts/mocks/MasterMock.sol
contracts/mocks/MemberRoles/MRMockCover.sol
contracts/mocks/MemberRoles/MRMockQuotationData.sol
contracts/mocks/MemberRolesMock.sol
contracts/modules/governance/MemberRoles.sol
contracts/modules/governance/VotePower.sol
lib/constants.js
test/unit/Assessment/castVotes.js
test/unit/Assessment/setup.js
test/unit/Assessment/withdrawRewards.js
test/unit/MemberRoles/changeAuthorized.js
test/unit/MemberRoles/changeDependentContractAddress.js
test/unit/MemberRoles/changeMaxABCount.js
test/unit/MemberRoles/index.js
test/unit/MemberRoles/join.js
test/unit/MemberRoles/setup.js
test/unit/MemberRoles/stateManagement.js
test/unit/MemberRoles/swapABMember.js
test/unit/MemberRoles/switchMembership.js
test/unit/MemberRoles/switchMembershipOf.js
test/unit/MemberRoles/updateRole.js
test/unit/MemberRoles/withdrawMembership.js
test/unit/TokenController/setup.js
test/utils/evm.js

Issue: #345 
Added unit test to increase the coverage of MomberRoles.
N/A

Test: Unit tests for Member Role

---

lib/constants.js
lib/helpers.js
test/unit/Pool/addAsset.js
test/unit/Pool/buyNXM.js
test/unit/Pool/calculateEthForNXM.js
test/unit/Pool/calculateNXMForEth.js
test/unit/Pool/calculateTokenSpotPrice.js
test/unit/Pool/getMCRRatio.js
test/unit/Pool/getPoolValueInEth.js
test/unit/Pool/getTokenPrice.js
test/unit/Pool/getters.js
test/unit/Pool/removeAsset.js
test/unit/Pool/sellNXM.js
test/unit/Pool/sellNXMTokens.js
test/unit/Pool/sendPayout.js
test/unit/Pool/setSwapDetailsLastSwapTime.js
test/unit/Pool/setSwapValue.js
test/unit/Pool/setup.js
test/unit/Pool/transferAsset.js
test/unit/Pool/transferAssetToSwapOperator.js
test/unit/Pool/updateParameters.js
test/unit/Pool/upgradeCapitalPool.js
test/unit/StakingPool/depositTo.js
test/utils/token-price.js

This PR replaces web3/truffle with ethers in all the capital pool unit tests

Chore: Change capital pool unit tests to use ethers instead of  web3/truffle

---

contracts/interfaces/ICoverMigrator.sol
contracts/interfaces/IMasterAwareV2.sol
contracts/modules/legacy/LegacyGateway.sol

Closes issue https://github.com/NexusMutual/smart-contracts/issues/620
- make all functions that would return misleading info return
- remove unused dependencies
- switch to MasterAware2 - TBD if feasible
Ran existing tests suite

Chore: Gateway cleanup

---

contracts/mocks/Testnet/TestnetClaimProofs.sol
contracts/mocks/Testnet/TestnetClaimsData.sol
scripts/deploy/deploy.js

ClaimsData and ClaimProofs were removed from the deploy script but they're by frontend for displaying legacy claims.
Created mocks for adding new claims and new proofs.
If it breaks - scream.

Fix: re-add legacy claim contracts to deploy script

---

contracts/interfaces/ICover.sol
contracts/modules/cover/Cover.sol
test/unit/Cover/burnStake.js
test/unit/Cover/setup.js
test/unit/CoverViewer/views.js
test/unit/IndividualClaims/getClaimsCount.js
test/unit/IndividualClaims/helpers.js
test/unit/IndividualClaims/redeemClaimPayout.js
test/unit/YieldTokenIncidents/redeemPayout.js

closing #566 
Adding `globalCapacityFactor` to segments of the Cover to be used when burning stake.
Test expanded with test with change of globalCapacityFactor before burn stake

Fix: Add the current globalCapacityFactor to store

---

contracts/interfaces/ICover.sol
contracts/interfaces/IStakingPool.sol
contracts/modules/cover/Cover.sol
contracts/modules/staking/StakingPool.sol
test/integration/Cover/createStakingPool.js
test/unit/Cover/buyCover.js
test/unit/Cover/editCover.js
test/unit/Cover/initialize.js
test/unit/Cover/setProductTypes.js
test/unit/Cover/setProducts.js
test/unit/StakingPool/depositTo.js
test/unit/StakingPool/extendDeposit.js
test/unit/StakingPool/initialize.js
test/unit/StakingPool/requestAllocation.js
test/unit/StakingPool/setPoolFee.js
test/unit/StakingPool/setPoolPrivacy.js
test/unit/StakingPool/setProducts.js
test/unit/StakingPool/withdraw.js

Closes #402 
Changed all require statements to throw a 4 byte custom error instead of the 32..n byte string errors.
Bytecode size with optimizer on:
Cover (before) : 23,478 Bytes
Cover (after):     21,466  Bytes
Staking (before): 25,849 Bytes
Staking (after): 23,572  Bytes
The chai matchers now expect custom errors to be used for Cover/StakingPool calls

Feature: Use custom errors instead of revert strings in Cover and StakingPool

---

contracts/interfaces/ICover.sol
contracts/modules/cover/Cover.sol
test/unit/Cover/editCover.js
test/unit/Cover/setup.js

Closes #559 
This PR adds a flag to the struct `PoolAllocationRequest` to be able to add a staking pool to the cover allocations. The flag signals that repricing/deallocating should be skipped, and the previous allocation on the staking pool should be carried over.
The unit tests at `test/unit/Cover/editCover.js` are updated and re-enabled.

Feature: Add flag to PoolAllocationRequest to skip pool during edit cover

---

contracts/interfaces/IStakingPool.sol
contracts/mocks/TokenControllerMock.sol
contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/burnStake.js
test/unit/StakingPool/index.js
test/unit/StakingPool/setup.js

Closes #562 
This PR adds a modifier to the staking pool, to block all deposits and cover buys on a staking pool if 100% of the active stake has been burned.
This is done to avoid division-by-zero issues.
A unit test was added at `StakingPool/burnStake.js`

Feature: Block deposits and allocations when 100% of stake is burned

---

contracts/mocks/NXMTokenMock.sol
test/unit/TokenController/burnFrom.js
test/unit/TokenController/changeOperator.js
test/unit/TokenController/index.js
test/unit/TokenController/mint.js
test/unit/TokenController/operatorTransfer.js

Partial implementation of https://github.com/NexusMutual/smart-contracts/issues/346
Built on top of https://github.com/NexusMutual/smart-contracts/pull/684 to avoid conflicts in the setup
Adds new unit tests for:
- changeOperator()
- operatorTransfer()
- mint()
- burnFrom()
New tests were added:
- `test/unit/TokenController/changeOperator.js`
- `test/unit/TokenController/operatorTransfer.js`
- `test/unit/TokenController/mint.js`
- `test/unit/TokenController/burnFrom.js`
* …

Test: Add token controller operator related methods unit tests

---

scripts/deploy/deploy.js
scripts/mocks/buyV1Covers.js
scripts/mocks/buyV2Covers.js
scripts/mocks/createStakingPools.js
scripts/mocks/depositToStakingPools.js
scripts/mocks/fund.js

Scripts required for UI mocks. 
Closes #664 
Depends on https://github.com/NexusMutual/smart-contracts/pull/639
Reimplementing existing scripts so deposits and buy covers work well.
You can run locally:
- `ABI_DIR=../frontend-react/src/constants/abis CONFIG_FILE=../frontend-react/config/local.json  node scripts/deploy/start.js`
Then:
- `HARDHAT_NETWORK=localhost CONFIG_FILE=$PWD/../frontend-react/config/local.json  node scripts/mocks/fund.js 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266`
- `HARDHAT_NETWORK=localhost CONFIG_FILE=$PWD/../frontend-react/config/local.json node scripts/mocks/createStakingPools.js`
- `HARDHAT_NETWORK=localhost CONFIG_FILE=$PWD/../frontend-react/config/local.json STAKER=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 node scripts/mocks/depositToStakingPools.js`
- …

Test: staking scripts for UI mocks

---

contracts/interfaces/ICover.sol
contracts/interfaces/IStakingPool.sol
contracts/mocks/Cover/CoverMockStakingPool.sol
contracts/modules/cover/Cover.sol
contracts/modules/staking/StakingPool.sol
test/integration/IndividualClaims/submitClaim.js
test/integration/utils/staking.js
test/unit/Cover/burnStake.js
test/unit/Cover/createStakingPool.js
test/unit/CoverViewer/views.js
test/unit/StakingPool/burnStake.js

Closes #632 
- `Cover.burnStake()`:
- Reduces coverSegmentAllocations `premiumInNXM` which is used for the refund calculation
- Builds the cover parameters to replicate the allocation request and pass it to `stakingPool.burnStake()` along with the reduced cover amount after the claim
- `StakingPool.burnStake()`:
- Calls `getActiveAllocationsWithoutCover()` and `allocate()` to reduce the allocation. Sets the current timestamp to the `segment.start` so the allocation is removed and set into the same tranches from the initial allocation
- Some internal methods were updated to have the timestamp as a parameter instead of using `block.timestamp` directly. This was needed for the previous item
- Added a new integration test for the specific scenario from the issue in …

Fix: Reduce cover allocation on burns

---

contracts/modules/staking/StakingViewer.sol

StakingViewer needs a function that returns all the pools for the product
StakingViewer expanded with `getProductPools` function.
N/A

Feature: `getProductPools` function

---

contracts/modules/governance/NXMaster.sol
test/integration/Master/master.js

Issue: https://github.com/NexusMutual/smart-contracts/issues/721
Add a test to verify the code that creates proxies with predictable addresess.
IMPORTANT. Production BUG FIX. Fix the solidity code path so it does not revert when the contractType field is encoding a salt to obtain a predictable proxy address.
Add a test for the above as described.

Test & Fix: NXMaster proxy creation with predictable address + fix for event emission

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/withdraw.js

Reward shares were set to zero when withdrawing rewards blocking subsequent withdrawals.
- Does not zero out the deposit reward shares when withdrawing rewards
- Correctly stores the `lastAccNxmPerRewardShare` for expired deposits (for consistency)
Added a test with two deposits, one being withdrawn a single time and the other two times, making sure the amounts are the same.

Fix withdraw() removing reward shares bug

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/depositTo.js

Closes issue https://github.com/NexusMutual/smart-contracts/issues/652
Check `msg.sender` is the staking NFT owner or approved when making a deposit to it.
Unit test

Feature: Validate staking nft owner at deposit 

---

contracts/modules/assessment/IndividualClaims.sol
contracts/modules/assessment/YieldTokenIncidents.sol
contracts/modules/cover/Cover.sol
test/integration/IndividualClaims/submitClaim.js
test/unit/Cover/buyCover.js
test/unit/Cover/editCover.js
test/unit/IndividualClaims/submitClaim.js

Cover edits where underflowing because of a mismatch between cover start in Cover contract (`block.timestamp + 1`) and cover start / rewards streaming start in StakingPool (`block.timestamp`).
This PR makes the cover start at `block.timestamp` and instead explicitly prevents claim submission in the same block.
* :thinking: = I don’t understand something, do you mind giving me more …

Fix: start covers at block timestamp

---

contracts/modules/cover/Cover.sol

Cover.sol was above size limit again.
Made `activeCoverExpirationBuckets` internal
N/A

Chore: Reduce Cover.sol size

---

scripts/mocks/buyV2Covers.js

Really small fix for the `buyV2Covers.js` script. Since the `ALLOCATION_UNITS_PER_NXM` function of the `Cover` contract is private now, it is mocked.

Replace ALLOCATION_UNITS_PER_NXM function with mock in buyV2Covers.js

---

contracts/modules/token/TokenController.sol
hardhat.config.js/solidity.js
hardhat.config.js/tasks.js
scripts/extract-storage-layout.js
test/fork/migration-v2.js
test/layout/index.js
test/layout/slots.js
test/layout/storage/v1.json

Closing: #609
Extracting Storage Layout from artifacts and using them to check the values on contracts using `getStorageAt` function before and after upgrade.
Fork test expanded with storage tests.

Migration: V2 migration fork test storage slots

---

scripts/products/generate-product-types-tx.js
test/fork/index.js
test/fork/product-type-update.js

On-chain the product type data is wrong. We stored grace period for product types in days not in seconds.
Add script to generate an update data for all the current product types, to update the information for grace Period more particularly, which is wrong (days instead of seconds).
Note: this only supports updates now to solve for this immediate use case. We can add support for inserting new product types in the future.
To run it locally you can do this:
```node scripts/products/generate-product-types-tx.js 0xcafeac0fF5dA0A2777d915531bfA6B29d282Ee62 0x87B2a7559d85f4653f13E6546A14189cd5455d45```
Which is assuming 0x87 is the AB signer.
Tested with a fork test.
* …

Feat: Script for setProductType tx generation

---

contracts/interfaces/IBrightUnionDistributor.sol
contracts/modules/cover/Cover.sol
test/fork/index.js
test/fork/migrated-claims.js
test/unit/Cover/totalActiveCoverInAsset.js

Fix issue with migrating a V1 cover to V2 where active cover amount is not properly increased.
Change Cover.sol to include the fix
Run a fork test to test the migrated covers for FTX and Euler Finance.

Increase total active cover amount when migrating covers

---

contracts/modules/staking/StakingViewer.sol

issue: #827 
Added bumpedPriceUpdateTime to the return of the getPoolProducts

getPoolProducts return expanded with `bumpedPriceUpdateTime`

---

contracts/interfaces/ITokenController.sol
contracts/mocks/MemberRoles/MRMockAssessment.sol
contracts/mocks/MemberRoles/MRMockPooledStaking.sol
contracts/mocks/TokenControllerMock.sol
contracts/modules/governance/MemberRoles.sol
test/fork/index.js
test/fork/withdraw-switch-membership-restrictions.js
test/unit/MemberRoles/setup.js
test/unit/MemberRoles/switchMembership.js
test/unit/MemberRoles/withdrawMembership.js

Issue: https://github.com/NexusMutual/smart-contracts/issues/832
Users shouldn't be able to switchMembership or withdrawMembership before they withdrew everything from V1 and from Assessment and Governance in V2.
Those holdings are strictly associated with their address, unlike the covers and Staking deposits which are NFTs.
Add require statements for both codepaths so that, staking deposits and rewards, tokens locked for claimed assessment and withdrawable cover notes are all 0.
Add extra unit tests for these clauses.
* :thinking: = I don’t understand …

Fix: add withdraw/switch membership restrictions

---

contracts/modules/cover/Cover.sol

Closes https://github.com/NexusMutual/smart-contracts/issues/810.
Needed to support calling of `isPoolAllowed` for multiple private products. This is needed for a FE check when displaying staking products list in the edit staking pool wizard. See https://github.com/NexusMutual/frontend-react/issues/958 for more details.
As described above
N/A

Chore: Add Multicall to the Cover contract

---

contracts/modules/cover/Cover.sol
test/unit/Cover/buyCover.js

Issue: #779 
Commission calculation changed from `x * (1 + commission)` to `x / (1 - commission)`
Tests for buy cover changed to check the change in commission calculation

Fix: Changing the commission calculation

---

scripts/products/generate-setProducts-tx.js

Add a script for just adding new products from a sheet.
Create an additional script that takes as input a CSV file as the one shown above, reads the product data and construct a Cover.setProducts tx to be executed by an AB member.
https://docs.google.com/spreadsheets/d/1aaAC3BOR66pzruKVpFcpAP6151w4x1teX3ERlJ9FuV8/edit#gid=0
Run the script and validate with tenderly transaction looks correct. (manual).

Chore: Add script for new products

---

contracts/interfaces/IStakingPool.sol
contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/processExpirations.js

Issue: #864 
Add event when bucket or tranche expires
Added tests to check if the event is emitted.

Feature: Add process expiration events

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/requestAllocation.js

Issue #872 
Carry over allocations from previous tranches.
Added a test that fails with the current release-candidate and passes with the fix.

Fix: allocation carry over

---

contracts/modules/capital/SwapOperator.sol
test/fork/index.js
test/fork/migrated-claims.js
test/fork/migration-v2.js
test/fork/product-type-update.js
test/fork/utils.js
test/fork/withdraw-enzyme-shares.js
test/fork/withdraw-switch-membership-restrictions.js
test/unit/SwapOperator/recoverAsset.js

Issues
https://github.com/NexusMutual/smart-contracts/issues/861
https://github.com/NexusMutual/smart-contracts/issues/451
Test how withdrawal of Enzyme would work and fix any bugs related to that.
Also add recovery of ETH from swap operator.
Fix the bug in SwapOperator where the denominator for the slippage calculation is 1e18 instead of 10000 (the correct value) for the 2 Enzyme calls.
Notes:
A withdrawal in any amount requires:
* changing Enzyme vault shares asset details min  to 0  and max to a value that's lower than the current shares amount (eg. 1) respectively.
* Upgrade SwapOperator to fix the denominator bug.
* Get Enzyme to enable the new SwapOperator as a Shares Receiver.
* call swapEnzymeVaultShareForETH with the current amount of shares (15348001519741036985819).
Expecting …

Fix: SwapOperator denominator bug + enzyme full withdrawal

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/helpers.js
test/unit/StakingPool/requestAllocation.js
test/unit/StakingProducts/initializeProducts.js

Due to a lax check on the expiration bucket id the expire cover could revert with an underflow since the allocations could have been already freed up.
This PR moves corrects the check and moves it earlier in the code to fail with a custom error instead.
Added a new test that:
1. Allocates a short cover in the current bucket
2. Moves to the next bucket
3. Tries to expire
Before the fix it will fail with an underflow, with the fix it fails with a custom error.
* :rocket: = …

Fix: Expiration bucket check on cover expiration

---

contracts/modules/cover/Cover.sol
test/integration/Cover/buyCover.js
test/integration/setup.js

Marking products as being fixed price is currently being skipped on allocation requests.
Set the useFixedPrice boolean on the allocationRequest on buy cover.
Added new tests to catch the issue

Bug: Fix fixed price product cover buys

---

contracts/modules/staking/StakingProducts.sol

When calling `calculateFixedPricePremium` we pass coverAmount and period in wrong order
Fix the arguments order in the `calculateFixedPricePremium` invoke

Fix `calculateFixedPricePremium` arguments

---

contracts/interfaces/INXMToken.sol
contracts/mocks/common/NXMTokenMock.sol
contracts/modules/token/TokenController.sol
test/unit/TokenController/mint.js
test/unit/TokenController/setup.js

Previously the mint function from TokenController did not check if the destination address is a member or not.
This PR introduces an internal function `_mint` that performs this checks. All other TC functions should use it instead of directly calling the token contract.
Added a new test to check for revert when the destination address is not a member.

Check membership when minting

---

Dockerfile
package-lock.json
package.json
scripts/deploy/deploy.js

The deployments `build.js` script now also outputs abi json files to `dist/data/abis/`. The `addresses.json` file is also moved to the `dist/data` folder (from the `dist` folder). Now the `@nexusmutual/sdk` package can copy them over and re-expose them. This is convenient for loading the abis with libs who require json files instead of javascript objects.
But the actual real reason this was changed is because this enables the `frontend-next` to load freshly generated abis via some `npm link` magic. Check [Notion](https://www.notion.so/nxmcommunity/Local-development-95f84f09cbfb4b90bcdcba52e1d2fa90?pvs=4) out for more info.
Note: this includes the Ramm contract.

Update deploy script + deployments build script

---

contracts/interfaces/IRamm.sol
contracts/modules/capital/Ramm.sol
test/integration/Ramm/swap.js
test/unit/Ramm/getInternalPrice.js
test/unit/Ramm/getInternalPriceAndUpdateTwap.js
test/unit/Ramm/getObservation.js
test/unit/Ramm/getReserves.js
test/unit/Ramm/getSpotPrices.js
test/unit/Ramm/helpers.js
test/unit/Ramm/storeState.js
test/unit/Ramm/swap.js
test/unit/Ramm/updateTwap.js
test/utils/internalPrice.js

Add EthInjected and EthExtracted to emit the exact values injected / extracted.
The events should only be emitted once per function call and only on mutative functions (i.e. on storeState).
See ticket #993 for the discussion of the solution
This is behind PR #1008 
* Add `EthInjected` & `EthExtracted` events
* Modify **adjustEth** and **_getReserves** to return injected and extracted values
* add emit EthInjected and EthExtracted events to the following mutative functions:
* swapEthForNxm
* swapNxmForEth
* updateTwap
* getInternalPriceAndUpdateTwap
* ramm.swapEthForNxm EthInjected & EthExtracted events tests
* ramm.swapNxmForEth EthInjected & EthExtracted events tests
* ramm.updateTwap EthInjected & EthExtracted events tests
* ramm.getInternalPriceAndUpdateTwap EthInjected & EthExtracted …

feat: Add EthInjected and EthExtracted events

---

contracts/interfaces/IMemberRoles.sol
contracts/modules/governance/MemberRoles.sol
test/integration/MemberRoles/withdrawMembership.js
test/unit/MemberRoles/withdrawMembership.js

Add MembershipWithdrawn event to help keep track of the current memberships
Closes #1039
Add MembershipWithdrawn event:
```solidity
event MembershipWithdrawn(address indexed member, uint timestamp);
```
* added MembershipWithdrawn event unit test
* added MembershipWithdrawn event integration test

feat: Add event MembershipWithdrawn

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/extendDeposit.js

Issue: #995 
Added a check if the token is locked before expanding the deposit

Fix: Add a check on expandDeposit if tokens are locked

---

deployments/build.js

We need const assertion of the abis for Wagmi type safety on FE.
Read more about this here: https://wagmi.sh/core/typescript#const-assert-abis-typed-data
Used the JSON abi files to create the abi const-assert object.
Run `npm run deployments:build `.
Check `generated/abis.ts` file. It should contain the abis with const assertion.

Add const assertion for generated abis

---

contracts/external/WETH9.sol
contracts/interfaces/IERC20.sol
contracts/libraries/external/SafeMath.sol
contracts/mocks/Pool/P1MockLido.sol
contracts/mocks/SwapOperator/SOMockEnzymeV4Vault.sol
contracts/mocks/TokenController/TCMockGovernance.sol
contracts/mocks/Tokens/ERC20CustomDecimalsMock.sol
contracts/mocks/Tokens/ERC20MintableDetailed.sol
contracts/mocks/Tokens/ERC20Mock.sol
contracts/mocks/Tokens/ERC20MockNameable.sol
contracts/mocks/Tokens/ERC20RevertingBalanceOfMock.sol
contracts/mocks/Tokens/ERC721.sol
contracts/mocks/Tokens/ERC721Mock.sol
contracts/mocks/common/ERC20Detailed.sol
contracts/mocks/common/ERC20Mintable.sol
contracts/mocks/common/NXMTokenMock.sol
contracts/modules/governance/Governance.sol
contracts/modules/legacy/LegacyClaimsData.sol
contracts/modules/legacy/LegacyQuotationData.sol
contracts/modules/token/external/Context.sol
contracts/modules/token/external/ERC20.sol
package-lock.json
package.json

Issue: #929 
- Remove solmate and @openzepelin v2 contracts
*Note: instead of copying the `SafeMath.sol` to the external directory in the governance, copied it to lib/external since other contracts use that are not in governance directory*
*Note: leaving `@openzeppelin/contracts-v4` as it is, if we rename it without the `-v4` it breaks the beacon proxy and it's bytecode so the StakingPool addresses are calculated wrong *
- N/A

Remove deps, and modify contracts to support the change

---

deployments/build.js
deployments/src/addresses.json

Issue: #1098 
Add CoverBroker to the list for deployment and it's address
N/A

Chore: Add CoverBroker to deployment

---

scripts/products/get-setProducts-txdata.js

Fix metadata file path for setProducts script
* Fix metadata file path for setProducts script
* manually tested

fix: Fix setProducts script metadata file path

---

contracts/modules/cover/Cover.sol
test/integration/Cover/expireCover.js

There was no space in the Cover.sol contract so we didn't update activeCover in expireCover , we left it to be done when the whole bucket expires. This creates the delay saving in active cover amount.
Issue: #1043
Add update to `activeCoverExpirationBuckets` and `activeCover` when expiring cover
* …

bug: Update missing updates when expiring cover

---

scripts/products/get-setProducts-txdata.js

Add tenderly simulation to setProducts script.
[Product listing docs](https://www.notion.so/nxmcommunity/Product-Product-Type-Listing-Requests-705a4bdfede842039a968558806741a2) have been updated accordingly
* Add tenderly simulation to setProducts script
* manual test

feat: Add tenderly simulation to setProducts script

---

contracts/interfaces/ICoverProducts.sol
contracts/interfaces/IStakingProducts.sol
contracts/mocks/generic/StakingProductsGeneric.sol
contracts/mocks/modules/Cover/COMockStakingProducts.sol
contracts/modules/cover/CoverProducts.sol
contracts/modules/staking/StakingProducts.sol
test/integration/setup.js
test/unit/Cover/setup.js
test/unit/CoverProducts/setProducts.js
test/utils/accounts.js

If `useFixedPrice` is set to `false`, while updating product there is no way to change allowed pools
closes #859
- Remove check for useFixedPrice to add allowed pools
- Add a validation of the allowedPools
- Update the allowedPools for product
- Added a new test for setting the product with invalid allowedPools

fix: separate allowed pools from fixed price

---

scripts/products/get-setProducts-txdata.js

Removes whitespaces to "Cover Assets" entry in the csv file
* add regex to remove whitespace
* tested regex locally

feat: Remove whitespace in Cover Assets csv

---

contracts/modules/staking/StakingPool.sol
package-lock.json
package.json
test/fork/basic-functionality-tests.js
test/fork/process-expiration.js
test/integration/setup.js

Closes #1151
See the above issue for detailed info
* Add check in `proccessExpirations` for pool 8 and rollback lastAccNxmUpdate to prevent underflow
* fork test

fix: Fix processExpiration for pool 8

---

contracts/interfaces/ICover.sol
contracts/interfaces/ICoverBroker.sol
contracts/interfaces/ICoverProducts.sol
contracts/interfaces/IIndividualClaims.sol
contracts/interfaces/IPooledStaking.sol
contracts/interfaces/IPriceFeedOracle.sol
contracts/interfaces/IRamm.sol
contracts/interfaces/IStakingNFTDescriptor.sol
contracts/interfaces/IStakingPool.sol
contracts/interfaces/IStakingProducts.sol
contracts/interfaces/IYieldTokenIncidents.sol
contracts/mocks/modules/Cover/COMockStakingPool.sol
contracts/mocks/modules/Incidents/ICMockCoverProducts.sol
contracts/modules/cover/CoverMigrator.sol
contracts/modules/staking/StakingNFTDescriptor.sol

#1121
Move enums and structs into their interfaces instead of having them at file level.
The `ClaimMethod` enum and the following structs that were left as is are because they're being referenced in other contracts.
```
ICoverProducts: ProductInitializationParams
IStakingPool: AllocationRequest, BurnStakeParams
IPool: SwapDetails, Asset
ICover: PoolAllocationRequest, BuyCoverParams, Product, ProductType, PoolAllocation, CoverData, CoverSegment
```
Note: There's also a workaround that can be used sometimes to avoid clashes in the future by importing only the desired symbols from the target file using the following syntax: `import { IIndividualClaims } from "./IIndividualClaims.sol";`. This way the `Configuration` struct wouldn't be imported. This won't always work, for example if you …

Chore: data types namespacing

---

contracts/interfaces/ICover.sol
contracts/interfaces/ICoverProducts.sol
contracts/mocks/generic/CoverProductsGeneric.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/CoverProducts.sol
scripts/migrate-cover-products-metadata.js
test/integration/Cover/buyCover.js
test/integration/StakingProducts/setProducts.js
test/unit/Cover/buyCover.js
test/unit/CoverProducts/setProductTypes.js
test/unit/CoverProducts/setProductTypesMetadata.js
test/unit/CoverProducts/setProducts.js
test/unit/CoverProducts/setProductsMetadata.js
test/unit/StakingPool/requestAllocation.js

Up until now the ipfs hashes of the products and product types were emitted as events which made it a bit more difficult for the frontend to fetch them without an indexer. Given those events are only triggered by AB members there aren't a lot of them.
This PR the ipfs hashes from being emitted as events into contract storage. Those can be added when adding/editing the product or product type or by pushing them individually without a product edit.
Added unit tests for all functions that deal with metadata as well as a migration script that fetches all events from the Cover contract and outputs the tx data that an AB can manually send to set the metadata in the CoverProducts contract.
* :cake: = Nice to …

Feature: Move ipfs hashes to storage

---

contracts/interfaces/INexusViewer.sol
contracts/interfaces/IStakingViewer.sol
contracts/mocks/modules/AssessmentViewer/AVMockAssessment.sol
contracts/mocks/modules/NexusViewer/NVMockAssessmentViewer.sol
contracts/mocks/modules/NexusViewer/NVMockStakingViewer.sol
contracts/modules/staking/StakingViewer.sol
contracts/modules/viewer/NexusViewer.sol
test/fork/utils.js
test/integration/Cover/buyCover.js
test/integration/NexusViewer/getClaimableNxm.js
test/integration/NexusViewer/getStakedNxm.js
test/integration/NexusViewer/setup.js
test/integration/setup.js
test/integration/utils/cover.js
test/unit/NexusViewer/getStakedNXM.js
test/unit/NexusViewer/setup.js
test/unit/StakingViewer/getManagedStakingPools.js
test/unit/StakingViewer/getManagerPoolsAndRewards.js
test/unit/StakingViewer/getManagerTokenRewards.js
test/unit/StakingViewer/processExpirationsFor.js
test/unit/StakingViewer/setup.js
test/utils/index.js
test/utils/stakingPool.js

Closes #1166 
Add NexusViewer to provide a unified view of system-wide data from various contracts within the Nexus Mutual platform
NOTE: this PR is behind https://github.com/NexusMutual/smart-contracts/pull/1164
* Add NexusViewer
* Add mocks
* Add fork tests
* Add unit tests
* Add fork tests
* Add unit tests

feat: Add NexusViewer

---

contracts/interfaces/IPriceFeedOracle.sol

Add `decimals` function to the `Aggregator` interface in the `IPriceFeedOracle.sol` file so the frontend can read it.

Add decimals function to Aggregator interface

---

test/fork/cover-products.js

The fork tests are missing tests for stored values of Staking Pools before and after upgrade
Add tests for staking pools in fork tests

test: cover products staking pool fork tests

---

scripts/products/get-setProductTypes-txdata.js
scripts/products/get-setProducts-txdata.js
scripts/products/helpers.js

Issue: #1131 
Change contract used in the script from Cover to CoverProducts
Testing on tenderly

feat: Use CoverProducts in listing scripts

---

scripts/governance/get-createProposalWithSolution-txdata.js
scripts/governance/helpers.js
scripts/governance/proposal-sample.json

We need a script to simulate and extract tx data for the governance proposal, so we can execute action easier
Add script to simulate and extract tx data for the governance proposal
N/A

chore: Add scripts for proposal simulations

---

contracts/interfaces/IAssessment.sol
contracts/interfaces/ITokenController.sol
contracts/mocks/generic/AssessmentGeneric.sol
contracts/mocks/generic/TokenControllerGeneric.sol
contracts/mocks/modules/AssessmentViewer/AVMockAssessment.sol
contracts/modules/assessment/Assessment.sol
test/unit/Assessment/castVotes.js
test/unit/Assessment/helpers.js
test/unit/Assessment/processFraud.js
test/unit/Assessment/unstakeFor.js
test/unit/Assessment/withdrawRewards.js
test/unit/Assessment/withdrawRewardsTo.js

Relates to: https://github.com/NexusMutual/smart-contracts/issues/1173
The methods for withdrawing NXM need to support address params so that another contract can do a batch withdrawal on behalf of the user.
Below is the list of methods (only `unstakeFor` is not implemented):
* `AS.unstakeFor`
* TC.withdrawPendingRewards
* stakingPool(poolId).withdraw
* TC.withdrawCoverNote
* TC.withdrawClaimAssessmentTokens
* legacyPooledStaking.withdrawForUser
* legacyPooledStaking.withdrawReward
NOTE: this PR is behind https://github.com/NexusMutual/smart-contracts/pull/1164
* add `unstakeFor`
* replace Assessment requires with custom errors
* add / update unit tests
* chore
* add Views / Mutative Function sections to ITokenController
* add method name on revert for TokenControllerGeneric for clarity
* …

feat: Add Assessment.unstakeFor method

---

contracts/interfaces/IStakingPool.sol
contracts/interfaces/IStakingProducts.sol
contracts/mocks/generic/StakingPoolGeneric.sol
contracts/mocks/generic/StakingProductsGeneric.sol
contracts/mocks/modules/Cover/COMockStakingPool.sol
contracts/mocks/modules/Cover/COMockStakingProducts.sol
contracts/modules/staking/StakingPool.sol
contracts/modules/staking/StakingProducts.sol
test/unit/StakingPool/burnStake.js
test/unit/StakingPool/depositTo.js
test/unit/StakingPool/extendDeposit.js
test/unit/StakingPool/initialize.js
test/unit/StakingPool/processExpirations.js
test/unit/StakingPool/requestAllocation.js
test/unit/StakingPool/setPoolFee.js
test/unit/StakingPool/setPoolPrivacy.js
test/unit/StakingPool/withdraw.js
test/unit/StakingPoolFactory/setup.js
test/unit/StakingProducts/createStakingPool.js
test/unit/StakingProducts/helpers.js
test/unit/StakingProducts/recalculateEffectiveWeight.js
test/unit/StakingProducts/setPoolMetadata.js
test/unit/StakingProducts/setProducts.js
test/unit/StakingProducts/setup.js

Staking pools' titles and descriptions are stored on ipfs and the contract only emits an event with the ipfs hash. Event fetching takes a looooooooooong time and we want to optimize this.
This PR moves the ipfs hashes from events to storage. The contract choice (`StakingProducts` instead of `StakingPool`) is due to the extremly limited space in `StakingPool`.
Added new unit tests and cleaned up staking pool unit tests.

Feat: Move staking pool metadata

---

contracts/modules/staking/StakingPool.sol
test/unit/StakingPool/burnStake.js

When a burn is triggered while the cover is in grace period the deallocation is redundant since it will be done when the bucket expiration is processed.
The newly added code skips deallocations if the cover is expired.
Added a test to ensure the allocations stay the same.

Fix: skip deallocations when burning in grace period

---

contracts/interfaces/IStakingProducts.sol
contracts/interfaces/IStakingViewer.sol
contracts/modules/staking/StakingProducts.sol
contracts/modules/staking/StakingViewer.sol
package-lock.json
package.json
test/unit/StakingViewer/getPool.js

Add a new field `metadataIpfsHash` to StakingViewer Pool struct
* Add a new field `metadataIpfsHash` to StakingViewer Pool struct
* add missing `view` modifier to StakingProducts.getPoolMetadata
* small lint fixes (spaces, modifier ordering)
* add unit test

feat: Add metadataIpfsHash to StakingViewer Pool struct 

---

scripts/create2/deploy.js
scripts/create2/find-salt.js

Making the dev UX better by only requiring contract name and address instead of the FQCN:address
* Modify --libary, -l flags to take in CONTRACT_NAME:ADDRESS
Tested manually

Modify -library flag to take contract name and address

---

hardhat-config/index.js
hardhat-config/solidity.js

1. If `cwd` was not the root directory, running `hh compile` would compile without optimizer enabled because `dotenv` wouldn't load `.env`. This fix ensures `.env` is always loaded, regardless of the `cwd`.
2. We had a leftover `Object.values(array)` in `solidity.js` that we no longer need (the compilers array was an object at some point).
```
cd test/
hh compile
```
this should result in no compilation warnings (contracts exceeding max size) which we'd get when compiling without optimizer enabled.

chore: ensure .env loading and cleanup compilers

---

docs/StakingPoolFactory.md

- [StakingPoolFactory Contract Developer Documentation](#stakingpoolfactory-contract-developer-documentation)
- [Overview](#overview)
- [Key Concepts](#key-concepts)
- [Staking Pool Creation](#staking-pool-creation)
- [Beacon Proxy](#beacon-proxy)
- [Operator Role](#operator-role)
- [Mutative Functions](#mutative-functions)
- [`changeOperator`](#changeoperator)
- [`create`](#create)
- [View Functions](#view-functions)
- [`stakingPoolCount`](#stakingpoolcount)
- [Events](#events)
- [Frequently Asked Questions](#frequently-asked-questions)
- [Who can create a staking pool?](#who-can-create-a-staking-pool)
- [What happens if the beacon address is incorrect?](#what-happens-if-the-beacon-address-is-incorrect)
- [How can the operator role be changed?](#how-can-the-operator-role-be-changed)
- …

docs: add StakingPoolFactory contract docs

---

docs/user-flows/cover-buyer.md
docs/user-flows/staker.md

- [NXM Staker User Flow Documentation](#nxm-staker-user-flow-documentation)
- [Table of Contents](#table-of-contents)
- [Overview](#overview)
- [What You Need to Know Before Staking](#what-you-need-to-know-before-staking)
- [Choosing a Staking Pool](#choosing-a-staking-pool)
- [1. Manager Fees](#1-manager-fees)
- [2. Products Covered by the Pool](#2-products-covered-by-the-pool)
- [3. Pool Utilization \& Risk Exposure](#3-pool-utilization--risk-exposure)
- [Key Concepts](#key-concepts)
- [How Staking, Underwriting \& Rewards Work](#how-staking-underwriting--rewards-work)
- [Tranches \& What Happens When They Expire](#tranches--what-happens-when-they-expire)
- [Depositing Mid-Tranche \& Withdrawal Timing](#depositing-mid-tranche--withdrawal-timing)
- [Checking When a Tranche Will …

docs: add staker user flow

---

contracts/interfaces/IAssessment.sol
contracts/mocks/generic/AssessmentGeneric.sol
contracts/modules/assessment/AssessmentViewer.sol
test/fork/basic-functionality-tests.js
test/integration/Assessment/processFraud.js
test/integration/Cover/totalActiveCover.js
test/integration/IndividualClaims/submitClaim.js
test/integration/MCR/updateMCR.js
test/integration/Master/emergency-pause.js
test/integration/Master/master.js
test/integration/NexusViewer/setup.js
test/integration/TokenController/setup.js
test/integration/TokenController/withdrawNXM.js
test/integration/setup.js
test/integration/utils/voteClaim.js
test/layout/slots.js
test/unit/IndividualClaims/getClaimsToDisplay.js
test/unit/IndividualClaims/setup.js

Fixing integration tests after cover edit changes.

[FF-ONLY] Tests: fix integration tests

---

contracts/interfaces/ICover.sol
contracts/interfaces/ILimitOrders.sol
contracts/mocks/generic/CoverGeneric.sol
contracts/mocks/modules/LimitOrders/LimitOrdersCoverMock.sol
contracts/modules/cover/Cover.sol
contracts/modules/cover/LimitOrders.sol
test/integration/LimitOrders/executeOrder.js

Two issues we currently have:
- When there is an order with initial cover buy and renewals, we don't pass an original cover ID when renewing, so the cover doesn't get edited, and we would have double covers for some period. The second renewal would fail because we have a check for the expiration by the initial cover ID that doesn't have a new cover linked to it, and limit order contract would see it as expired, and the renewal wouldn't happen.
- When renewing a cover (edit), since we don't pass the original cover ID, we never get to check the approval and ownership of the cover. And it fails since the msg.sender is the LimitOrders contract and not the owner of the cover. 
- Created `_params` that copy arguments from `params` passed to the execute function and add coverId if the cover was …

fix: renewal of a cover that was bought with limitOrders

---

contracts/interfaces/ICoverProducts.sol

Add yield token incident claim method type back and mark it as deprecated
Removed enum value made getProductType calls fail because of claim method being `1` in contract storage on mainnet. Adding it back to address the issue.
:warning:  If there's nothing failing on-chain we may keep this for the next release, otherwise we may consider a hotfix.

fix: add yield token incident claim method type back

---

.github/workflows/release-next.yml
.github/workflows/release.yml

* add release-next workflow
* add release workflow
Please refer to the description w/in each file for a more detailed info.
**NOTE:** this [workflows PR](https://github.com/NexusMutual/workflows/pull/8/files) needs to be merged first 
* tested the flows in test-ci-1 repo

ci: add release and release next workflows

---

contracts/interfaces/ICover.sol

Add `CoverEdited` back to `ICover` for legacy support.

chore: add back the CoverEdited event so frontend can use it

---

contracts/interfaces/ICover.sol
contracts/modules/cover/Cover.sol
test/unit/Cover/editCover.js

Had to move some of the logic from the `_requestDeallocation` function into the calling function to avoid reading the cover twice from the storage.

chore: add cover asset check on edit

---

contracts/abstract/RegistryAware.sol
contracts/interfaces/IAssessment.sol
contracts/mocks/generic/AssessmentGeneric.sol
contracts/mocks/modules/Claims/CLMockAssessment.sol
contracts/modules/assessment/Assessment.sol
contracts/modules/assessment/Claims.sol
contracts/modules/governance/Registry.sol
test/unit/Assessment/closeVotingEarly.js
test/unit/Assessment/getAssessmentResult.js

* rename `PAUSE_CLAIM_PAYOUTS` to more generic `PAUSE_CLAIMS` as we are also using it on submitClaims
* drop `cooldownEnd` return value on `getAssessmentResult` - clean up
* unit tests

refactor: clean up Assessment and Claims
